<?php

# language dependent text used in the interface for users (not admin)

$strCharSet             = 'UTF-8';
$strLancode             = 'sq'; ## two letter iso code
$strLandir              = 'ltr'; ## language direction (ltr or rtl)
$strName                = 'Emri';
$strAddress             = 'Adresa';
$strEmail               = 'Adresa e emailit';
$strTown                = 'Qyteti';
$strPostcode            = 'Kodi Postar';
$strSubscribeInfo       = '<h3>Abonohu në buletinin tonë informativ </h3>';
$strRequired            = 'Fushat e kërkuara janë me shenjë të kuqe';
$strSubscribeTitle      = 'Abonohu në newsletter-in tonë ';
$strPleaseSelect        = 'Ju lutem zgjidhni buletinët informativë ku dëshironi të regjistroheni .';
$strSubmit              = 'Abonohu tek buletinët informativ të zgjedhur';
$strNotAvailable        = 'Na vjen keq por nuk ka buletin informativ të disponueshëm';
$strEnterName           = 'Ju lutemi të shkruani emrin';
$strEnterEmail          = 'Ju lutemi të vendosni një adresë emaili të vlefshëm';
$strConfirmEmail        = 'Konfirmo adresen e emailit';
$strInvalidHostInEmail  = 'Na vjen keq, por emaili në atë domain nuk dërgohet dot, kontrolloni nëse keni shkruar adresen e saktë të emailit';
$strEnterList           = 'Zgjidhni një buletin informativ për tu regjistruar';
$strPleaseEnter         = 'Ju lutem shkruani';
$strCheckbox            = 'Kjo fushë është e kërkuar: ';
# the thanks message can contain placeholders
#$strThanks              = 'Dear [FIRST NAME], <br/>Thank you for subscribing to our lists.';
$strThanks              = 'Faleminderit që u abonuat për buletinin tonë informativ.';
# the EmailConfirmation message can contain placeholders
#$strEmailConfirmation   = 'Your email [email] has been added to our system. You will be e-mailed shortly with confirmation of the lists you 
have subscribed to.';
$strEmailConfirmation   = 'Adresa juaj e emailit është shtuar në emailin tonë. Ju do të merrni një mesazh me kërkesën për të konfirmuar 
anëtarësinë tuaj. Ju lutemi të siguroheni që të klikoni linkun në email për të konfirmuar abonimin në buletinin informativ.';
$strEmailFailed          = 'Na vjen keq, por dërgimi i mesazhit për të kërkuar konfirmimin tuaj dështoi. Ju lutemi klikoni "Reload" për të 
provuar përsëri. Nqs akoma nuk punon, kontaktoni administratorin.';
$strUnsubscribeTitle    = 'Unsubscribe from our Newsletters';
$strUnsubscribeDone     = 'You have been unsubscribed from our newsletters and you will receive a confirmation message shortly.';
$strUnsubscribedNoConfirm = 'You have been unsubscribed from this newsletter system';
$strBack                = 'Back';
$strUnsubscribeInfo     = 'Ç\'regjistrohuni nga buletini informativ';
$strContinue            = 'Vazhdo';
$strUnsubscribeSelect   = 'Zgjidhni buletinët informativë nga të cilët doni të ç\'regjistrohuni';
$strAllLists            = 'Të gjitha listat';
$strNoLists             = 'Ansjëra nga ato';
$strUnsubscribeRequestForReason = 'Na vjen keq të mësojmë që nuk jeni më i interesuar në buletinin tonë informativ. Në mënyrë që të na ndihmoni 
të përmirësojmë shërbimet tona, do ua dinim për nder nëse na thoni arsyet pse:';
$strUnsubscribeFinalInfo = '<br/><b>Vini re</b>: Kjo faqe është që ju të ndaloni <b> përgjithmonë</b> të merrni emaile nga sistemi ynë i 
buletinit informativ. Nëse dëshironi të ndërroni adresen e emailit, ose të ndryshoni nga cilët buletinë dëshironi të merrni emaile, ju lutemi 
të  <a href="[PREFERENCESURL]"> përditësoni preferencat tuaja</a> ';
$strNoListsFound        = 'Na vjen keq, ju nuk jeni abonuar te ndonjë nga buletinët tona informative me këtë adrese emaili.';
$strResubmit            = 'Ridërgo';
$strUnsubscribeSubmit   = 'Ç\'regjistrohuni nga buletinët informativë të zgjedhur';
$strValuesMissing       = 'Mungojnë këto vlera të kërkuara';
$strConfirmInfo         = 'Faleminderit që konfirmuat abonimin në buletinët tona informative. Buletinët ku ju jeni i abonuar janë të listuara 
më poshtë:';
$strAlreadyConfirmed    = 'Ne tashmë e kemi marrë konfirmimin tuaj në të kaluarën.';
$strConfirmTitle        = 'Faqja e konfirmimit të anëtarësisë në phpList';
$strUserNotFound        = 'Abonenti nuk u gjet';
$strUserAlreadyInitialised = 'Na vjen keq, por fjalëkalimi është tashmë i vendosur.';
$strConfirmFailInfo     = 'Na vjen keq, por kërkesa juaj për konfirmim nuk mund të njihej. Ju lutemi të siguroheni që të përdorni adresen e 
plotë të web-it si të përmendur në emailin që keni marrë. Ndonjëherë, kjo adrese webi është në disa rreshta.';
$strPreferHTMLEmail     = 'Preferoj të marr emaile në formatin HTML';
$strPreferTextEmail     = 'Preferoj të marr emaile në formatin Tekst';
$strPreferredFormat      = 'Formati i preferuar për emailet:';
$strText                 = 'Text';
$strHTML                = 'HTML';
$strPreferencesTitle    = 'Përditësoni preferencat tuaja';
$strPreferencesInfo     = 'Ju lutemi të konfirmoni që informacioni i mëposhtëm është i saktë dhe klikoni në butonin "përditëso"';
$strUpdatePreferences   = 'Përditëso';
$strPreferencesEmailChanged = 'Adresa juaj e emailit është ndryshuar. Vizitoni linkun në emailin që do të merrni për të konfirmuar adresen e re 
të emailit';
$strYouAreBlacklisted = 'Adresa juaj e emailit është e listuar në listen tonë "Mos i dërgo", që do të thotë se ju na keni kërkuar neve që të 
mos ju dërgojmë më kurrë emaile. <br/>
Në mënyrë që të merrni sërish emaile nga buletini ynë, kërkohet ndërhyrje manuale nga ana e administratorit. Ju lutem na kontaktoni sërish duke 
deklaruar se dëshironi të merrni sërish emaile.';
$strPreferencesNotificationSent = 'Do të merrni një njoftim me ndryshimet.';
$strPreferencesUpdated = 'Faleminderit. E kemi përditësuar informacionin tuaj.';
$strClickHere          = 'Kliko këtu';
$strThisLink           = 'këtë link';
$strToUnsubscribe      = 'Në qoftë se nuk do të merrni më emaile nga buletini, ';
$strToUpdate           = 'Për të përditësuar preferencat ose për tu ç\'regjistruar vizitoni';
$strSendHTML           = 'Dërgo email HTML';
$strYes                = 'Po';
$strNo                 = 'Jo';
$strUnsubscribe        = 'Ç\'regjistrohu';
$strAllMailinglists    = 'Të gjithe buletinët informativ';
$strAttachmentIntro     = 'Ky mesazh përmban attachments dhe mund të shikoet me një shfletues web:';
$strLocation           = 'Vendodhja';
$strFrequency           = 'Sa shpesh dëshiron tju dërgojmë emaile';
$strHourly             = 'Çdo orë';
$strDaily               = 'Çdo ditë';
$strWeekly             = 'Çdo javë';
$strMonthly             = 'Çdo muaj';
$strChoosePassword      = 'Zgjidhni një fjalëkalim';
$strConfirmPassword    = 'Konfirmo fjalëkalimin';
$strEnterPassword       = 'Vendosni fjalëkalimin';
$strForgotPassword     = 'Harrova fjalëkalimin';
$strForgotPasswordEmailBody = '
    I dashur Mailinglist Master

    Kam harruar fjalëkalimin për  phpList mailinglist system.
    A mund ta ndryshosh dhe të më tregoni më pas se si është?

    Faleminderit
';

$strPassword           = 'Fjalëkalimi';
$strPassword2           = 'Konfirmo fjalëkalimin';
$strPasswordsNoMatch    = 'Fjalëkalimet nuk janë njëlloj';
$strEmailsNoMatch     = 'Adresat e emaileve që vendose nuk përputhen';
$strEmailNotValid  = 'Adresa e emailit nuk është e vlefshme';
$strInvalidPassword     = 'Gabim: email ose fjalëkalim jo i vlefshëm';
$strPasswordSent        = 'Fjalëkalimi juaj është dërguar. Do ta merrni në pak minuta në vazhdim.';
$strPasswordRemindSubject = 'Fjalëkalimi juaj për buletinët informativë';
$strPasswordRemindMessage = 'Fjalëkalimi juaj është ';
$strPasswordRemindInfo = 'Për të marrë fjalëkalimin me email, ju lutemi të shkruani adresen e emailit dhe të klikoni në butonin 
"'.$strForgotPassword.'" .';
$strLogin               = 'Hyr';
$strLoginTitle          = 'Ju lutemi të shkruani adresen e emailit dhe fjalëkalimin tuaj';
$strLoginInfo           = 'Kjo faqe kërkon një fjalëkalim. Ju lutemi të shkruani adresen e emailit dhe fjalëkalimin tuaj ';
$strPersonalLocationInfo = '
  <p>Kjo faqe kërkon identifikim personal që mund të gjendet tek çdo mesazh që merr.</p>
  <p>Në qoftë se ke klikuar këtë lokacion dhe merr këtë error, ju lutem siguroheni që të bëni paste të gjithë rreshtin në kutinë e lokacionit 
në shfletues. 
  Lokacioni ndonjëherë është në disa rreshta.</p>
  <p>Nëse nuk e di lokacionin, vendos adresen e emailit në kuti dhe kliko "Vazhdo"</p>
';
$strPersonalLocationSent = '<h3>Sukses! Ju do të merrni një mesazh me lokacionin tuaj personal shumë shpejt</h3>';
$strUserExists   = 'Një abonues me atë adrese emaili ekziston tashmë, dhe rekordet tona kanë një fjalëkalim të ndryshëm';
$strUserExistsExplanationStart = 'Në mënyrë që të merrni fjalëkalimin, kliko ';
$strUserExistsExplanationLink = 'këtu';
$strUserExistsExplanationEnd = ' për të shkuar te faqja ku mund të kërkosh lokacionin personal';
$strExplainBlacklist = 'Adresa e emailit që shkruan këtu do të ruhet në bazen tonë të të dhënave me qëllimin e vetëm të bllokimit të emaileve 
që vinë nga ky sistem.';

$strUserExistsResubscribe = 'Një abonues me atë adrese emaili ekziston tashmë';
$strUserExistsResubscribeExplanation = 'Vizitoni <a href="%s">faqen e preferencave</a> për të përditësuar informacionin tuaj.';


$strForwardTitle = 'Ridërgoje emailin tek dikush tjetër';
$strForwardSubtitle = 'Ridërgim i emailit tek dikush tjeter me subjekt ';
$strForwardEnterEmail = 'Ju lutemi të shkruani një email të vlefshëm për ta bërë forward';
$strForwardInvalidEmail = '%s nuk është një adresë emaili e vlefshme';
$strForwardBlacklistedEmail = 'Marrësi ka kërkuar të mos marrë emaile nga ky sistem.';
$strForwardEnterEmails = 'Ju lutem vendosni një numër maksimum për adresa emaili të vlefshme %s për të bërë forward';
$strForwardPersonalNote = 'Mund të vendosni një mesazh tekst (me numër maksimal karakteresh %d ) që do ti shtohet emailit që bëhet forward ';
$strForwardSuccessInfo ='Ky email nuk është bërë forward';
$strForwardFailInfo = 'Dështoi forwardi për emailin';
$strForwardAlreadyDone = 'Ky mesazh është bërë forward me sukses tek kjo adrese emaili';
$strForwardCountReached = 'Sasia maksimale e forwards është arritur';
$strForwardNoteLimitReached = 'Gjatësia maksimale e shënimeve personale është arritur';
$strForwardFooter = 'Ky mesazh është bërë forward te ti nga [FORWARDEDBY].
  Ti nuk je abononuar në mënyre automatike në këtë buletin informativ.
  Për tu abonuar në këtë buletin informativ shko tek';
$strForward = 'Forward';
$strFwd = 'Fwd'; # versioni i shkurtër për forward
$strContactAdmin = 'Kontaktoni administratorin';


?>

