<?php
# language dependent text used in the interface for users (not admin)
# Bosnian translation by Mirsad Hadzajlic m.hadzajlic@yahoo.com
# V. 11.03.06-01 /PHPlist 2.10.2
$strCharSet             = 'UTF-8';
$strLancode             = 'ba'; ## two letter iso code
$strLandir              = 'ltr'; ## language direction (ltr or rtl)
$strName                = 'Ime i prezime';
$strAddress             = 'Adresa';
$strEmail               = 'Email adresa';
$strTown                = 'Mjesto';
$strPostcode            = 'Poštanski broj';
$strSubscribeInfo       = '<h3>Upišite se u naše mailing-liste</h3>';
$strRequired            = 'Obavezna polja su označena crvenom bojom';
$strSubscribeTitle      = 'Upis u naše mailing-liste';
$strPleaseSelect        = 'Molimo da odaberete liste u koje se želite upisati';
$strSubmit              = 'Upis u odabrane mailing-liste';
$strNotAvailable        = 'Trenutno, nažalost, nemamo nijednu mailing-listu na ponudi za upis.';
$strEnterName           = 'Molimo da upišete vaše ime';
$strEnterEmail          = 'Molimo da upišete validnu email adresu';
$strConfirmEmail        = 'Potvrdite svoju email adresu';
$strInvalidHostInEmail  = 'Nažalost, email ka domeni koju ste naveli ne može se poslati; molimo da još jedanput provjerite da li ste ispravno upisali email adresu.';
$strEnterList           = 'Molimo da izaberete mailing-listu u koju se želite upisati';
$strPleaseEnter         = 'Molimo unesite';
# the thanks message can contain placeholders
#$strThanks             = 'Poštovani [FIRST NAME], <br/>hvala što ste se upisali u naše mailing-lista.';
$strThanks              = 'Hvala Vam za upis u naše mailing-liste.';
# the EmailConfirmation message can contain placeholders
#$strEmailConfirmation  = 'Vaša email adresa [email] je upisana u naš sustav oglasne e-pošte. Uskoro ćete dobiti email poruku sa potvrdom oglasnih lista u koje ste se upisali.';
$strEmailConfirmation   = 'Vaša email adresa je upisana u naš sustav oglasne e-pošte. Uskoro ćete primiti poruku sa zahtjevom da potvrdite svoje članstvo. Da biste potvrdili svoj upis, molimo da ne propustite kliknuti na link u toj poruci.';
$strEmailFailed         = 'Nažalost, slanje poruke sa zahtjevom za potvrdu vašeg upisa nije uspjelo. Pokušajte ponovo osvježivanjem stranice. Ako to nije pomoglo, molimo da kontaktirate administratora.';
$strUnsubscribeTitle    = 'Ispis iz naših mailing-lista';
$strUnsubscribeDone     = 'Ispisani ste iz naših mailing-lista i uskoro ćete dobiti potvrdnu poruku o tome.';
$strUnsubscribedNoConfirm = 'Ispisani ste iz ovog mailing-list sistema';
$strBack                = 'Natrag';
$strUnsubscribeInfo     = 'Ispis iz naših mailing-lista';
$strContinue            = 'Nastavak';
$strUnsubscribeSelect   = 'Molimo da izaberete mailing-liste iz kojih se želite ispisati';
$strAllLists            = 'Sve liste';
$strNoLists             = 'Nijedna';
$strUnsubscribeRequestForReason = 'Žao nam je što više niste zainteresirani da primate naša pisma s novostima. Da bismo poboljšali kvalitet naših sadržaja, biće nam drago da nam kažete zašto:';
$strUnsubscribeFinalInfo = '<br/><b>Molimo uzmite u obzir da</b>: putem ove web-stranice vi <b>definitovno</b> zaustavljate prijem emaila iz našeg sustava za slanje e-novosti. Ukoliko možda želite da promijenite vašu email adresu ili da promijenite e-novosti koje primate, umjesto toga možete <a href="[PREFERENCESURL]">ovdje unijeti željene promjene</a>';
$strNoListsFound        = 'Vi, nažalost, niste upisani ni u jednu našu mailing-listu sa ovom email adresom.';
$strResubmit            = 'Ponovno slanje';
$strUnsubscribeSubmit   = 'Ispis iz odabranih lista za e-novosti';
$strValuesMissing       = 'Slijedeći obavezni podaci nisu uneseni';
$strConfirmInfo         = 'Hvala što ste potvrdili svoj upis u naše mailing-liste. Spisak mailing-lista u koje ste upisani je slijedeći:';
$strAlreadyConfirmed    = 'Mi smo već ranije primili vašu potvrdu.';
$strConfirmTitle        = 'Stranica za potvrdu članstva u mailing-listi';
$strUserNotFound        = 'Nemamo takvog korisnika(ce)';
$strUserAlreadyInitialised = 'Izvinite, vaša lozinka je već postavljena';
$strConfirmFailInfo     = 'Nažalost, vaš zahtjev za potvrdu upisa nije prepoznat. Molimo da provjerite da li ste koristili punu web-adresu, onako kako je poslana emailom. Nekad se ova web-adresa prelomi u više redaka.';
$strPreferHTMLEmail     = 'Radije primam poruke u HTML formatu';
$strPreferTextEmail     = 'Radije primam poruke u TEXT formatu';
$strPreferredFormat     = 'Zadani format email poruka:';
$strText                = 'TEXT';
$strHTML                = 'HTML';
$strPreferencesTitle    = 'Ažurirajte svoje postavke';
$strPreferencesInfo     = 'Molimo da provjerite ispravnost donjih podataka i onda kliknete na komandu "Ažuriraj"';
$strUpdatePreferences   = 'Ažuriraj';
$strPreferencesEmailChanged = 'Vaša email adresa je promijenjena. Molimo da kliknete na link u emailu koji ćete dobiti kako biste potvrdili vašu novu email adresu';
$strYouAreBlacklisted       = 'Vaša email adresa se nalazi u našoj "Ne šalji" listi, što znači da ste od nas tražili da vam više ne šaljemo nikakve poruke sa e-novostima. <br/> Da biste ponovo primali naše obavijesti, potrebna je ručna intervencija od strane našeg administratora. Ukoliko to želite, molimo da nas kontaktirate sa izričitim zahtjevom da ponovo želite primati email poruke sa novostima. ';
$strPreferencesNotificationSent = 'Primićete izvještajnu poruku o promjenama koje ste unijeli.';
$strPreferencesUpdated = 'Hvala. Vaši podaci su sada ažurirani.';
$strClickHere          = 'Kliknite ovdje';
$strThisLink           = 'ovaj link';
$strToUnsubscribe      = 'Ukoliko više ne želite da primate pisma sa novostima, ';
$strToUpdate           = 'Da biste ažurirali svoje upisane postavke, ili se ispisali, molimo da posjetite';
$strSendHTML           = 'Pošalji email u HTML formatu';
$strYes                = 'Da';
$strNo                 = 'Ne';
$strUnsubscribe        = 'Ispiši me';
$strAllMailinglists    = 'Sve mailing-liste';
$strAttachmentIntro    = 'Ovaj email sadrži dodatke koji se mogu pregledati u web-pregledniku (browseru):';
$strLocation           = 'Lokacija';
$strFrequency          = 'Kako često vam šaljemo poruke';
$strHourly             = 'Svaki sat';
$strDaily              = 'Dnevno';
$strWeekly             = 'Sedmično';
$strMonthly            = 'Mjesečno';
$strChoosePassword     = 'Molimo izaberite neku lozinku';
$strConfirmPassword    = 'Potvrdite svoju lozinke';
$strEnterPassword      = 'Molimo unesite svoju lozinku';
$strForgotPassword     = 'Zaboravio/la sam lozinku';
$strForgotPasswordEmailBody = '
    Poštovani ravnatelju mailing-liste,

    Zaboravi(o/la) sam svoju lozinku.
    Molim Vas da ju obnovite i o tome me obavijestite.

    Unaprijed se zahvaljujem
';    
$strPassword           = 'Lozinka';
$strPassword2          = 'Potvrda lozinke';
$strPasswordsNoMatch   = 'Upisane lozinke nisu istovjetne';
$strEmailsNoMatch      = 'Email adrese se ne poklapaju';
$strEmailNotValid      = 'Email adresa nije validna';
$strInvalidPassword    = 'Greška: nije validna email adresa ili lozinka';
$strPasswordSent       = 'Vaša lozinka je poslana. Trebalo bi da ju dobijete za nekoliko minuta.';
$strPasswordRemindSubject = 'Vaša lozinka za naše mailing-liste';
$strPasswordRemindMessage = 'Vaša lozinka je:';
$strPasswordRemindInfo = 'Da biste dobili lozinku emailom, molimo da unesete vašu email adresu i da kliknete na "'.$strForgotPassword.'"';
$strLogin              = 'Prijava';
$strLoginTitle         = 'Molimo unesite svoju email adresu i lozinku';
$strLoginInfo          = 'Ova stranica zahtijeva lozinku. Molimo unesite svoju email adresu i lozinku';
$strPersonalLocationInfo = '
  <p>Ova stranica zahtijeva jednu osobnu identifikacijsku oznaku, koja se  može naći u porukama koje ste dobivali.</p>
  <p>Ukoliko ste kliknuli na lokaciju sa tom oznakom, i onda naišli na ovu grešku, molimo da se uvjerite da ste unijeli cijeli redak u
  adresno polje vašeg web-preglednika. Nekad se desi da adresna lokacija u email poruci dođe prelomljena u nekoliko redaka.</p>
  <p>Ukoliko ne znate tu lokaciju, unesite ovdje svoju email adresu i kliknite "Nastavak"</p>
';
$strPersonalLocationSent = '<h3>Uspješno obavljeno! Uskoro bi trebalo da dobijete poruku sa svojom osobnom lokacijom.</h3>';
$strUserExists           = 'Korisnik sa datom email adresom je već upisan, a u našoj arhivi se nalazi jedna drugačija lozinka';
$strUserExistsExplanationStart = 'Želite li dobiti svoju lozinku, kliknite ';
$strUserExistsExplanationLink  = 'ovdje';
$strUserExistsExplanationEnd   = ' da biste došli na stranicu gdje možete zatražiti svoju osobnu lokaciju';
$strExplainBlacklist           = 'Email adresa koju ovdje unesete će biti spremljena u našu datoteku sa jedinom svrhom da blokira bilo koji se na istu pošalje putem ovog email sistema.';

$strUserExistsResubscribe = 'Korisnik sa datom email adresom je već upisan';
$strUserExistsResubscribeExplanation = 'Posjetite <a href="%s">stranicu zadanih postavki</a> kako biste ažurirali svoje podatke.';


$strForwardTitle       = 'Proslijedi poruku nekom drugom';
$strForwardSubtitle    = 'Proslijedi poruku sa naznakom predmeta ';
$strForwardEnterEmail  = 'Molimo da unesete validnu email adresu na koju želite proslijediti poruku';
$strForwardInvalidEmail = '%s nije validna email adresa';
$strForwardBlacklistedEmail = 'Primatelj je zatražio da ne prima poruke iz ovog email sistema.';
$strForwardEnterEmails  = 'Molimo u ovo polje unesite maksimalno %s validnih email adresa za proslijedbu poruke, i to u svaki redak po jednu';
$strForwardPersonalNote = 'Možete unijeti jednostavnu tekstualnu poruku (maksimalno %d znakova) koja će biti pred-dodana u proslijeđenu email poruku.';
$strForwardSuccessInfo  = 'Poruka je proslijeđena';
$strForwardFailInfo     = 'Proslijeđivanje poruke nije bilo uspješno';
$strForwardAlreadyDone  = 'Ova poruka je već jedanput uspješno proslijeđena na datu email adresu';
$strForwardCountReached = 'Dostignut je maksimalni broj proslijeđivanja';
$strForwardNoteLimitReached = 'Dostignuta je maksimalna dužina osobne bilješke';
$strForwardFooter = 'Ova poruka vam je proslijeđena putem [FORWARDEDBY].
  Vi niste automatski upisani u ovu mailing-listu.
  Da biste se upisali u ovu mailing-listu otiđite na';
$strForward = 'Proslijedi';
$strFwd = 'Fwd'; # short version of forward for email subject


?>