<?php

# language dependent text used in the interface for users (not admin)

$strCharSet             = 'UTF-8';
$strName                = 'Ime';
$strAddress             = 'Adresa';
$strEmail               = 'E-mail';
$strTown                = 'Grad';
$strPostcode            = 'Poštanski broj';
$strSubscribeInfo       = 'Prijavite se na jedan ili više Newsletter upisivanjem u formu ispod';
$strRequired            = 'Obavezno polje';
$strSubscribeTitle      = 'Prijavite se na naše Newslettere';
$strPleaseSelect        = 'Molimo izaberite Newslettere na koje se želite prijaviti';
$strSubmit              = 'Prijavi me';
$strNotAvailable        = 'Nažalost, trenutno niti jedan Newsletter nije dostupan';
$strEnterName           = 'Molimo unesite Vaše ime';
$strEnterEmail          = 'Molimo unesite Vašu e-mail adresu';
$strInvalidHostInEmail  = 'Nažalost, e-mail se ne može dostaviti na tu domenu, provjerite dali ste unijeli ispravnu e-mail adresu';
$strEnterList           = 'Please select a newsletter to subscribe to';
$strPleaseEnter         = 'Molimo unesite';
# the thanks message can contain placeholders
#$strThanks              = 'Hvala Vam na upisivanju u našu mailing listu.';
$strThanks              = 'Hvala Vam na upisivanju u našu mailing listu.';
# the EmailConfirmation message can contain placeholders
#$strEmailConfirmation   = 'Vaš e-mail [email] je dodan u naš sistem. Uskoro ćete dobiti e-mail sa potvrdom lista na koje ste se upisali.';
$strEmailConfirmation   = 'Vaš e-mail [email] je dodan u naš sistem. Uskoro ćete dobiti e-mail sa zahtjevom da potvrdite vaše članstvo. Molimo kliknite na link u poruci kako biste potvrdili učlanjenje.';
$strEmailFailed          = 'Nažalost, slanje e-maila kojim bi zatražili vašu potvrdu nije uspijelo, molimo klikniti "Reload" ili "Refresh" kako biste pokušali ponovo. Ako i to ne upali, može biti zbog toga što se nalazite na našoj "Crnoj listi", što znači da ne možete dobivati e-mailove od našeg newsletter sistema. U tom slučaju, molimo kontaktirajte administratora.';
$strUnsubscribeTitle    = 'Odjavite se sa naših Newslettera';
$strUnsubscribeDone     = 'Odjavljeni ste sa naših Newslettera i ubrzo ćete dobiti e-mail potvrde.';
$strBack                = 'Nazad';
$strUnsubscribeInfo     = 'Odjavite se sa naših Newslettera';
$strContinue            = 'Nastavi';
$strUnsubscribeSelect   = 'Molimo izaberite Newslettere sa kojih se želite odjaviti';
$strAllLists            = 'Sve liste';
$strNoLists             = 'Niti jedna od njih';
$strUnsubscribeRequestForReason = 'Žao nam je što niste više zainteresirani za naš newsletter. Kako biste nam pomogli poboljašati naše usluge, bili bismo zahvali ako biste nam rekli zašto:';
$strUnsubscribeFinalInfo = '<br/><b>Napomena</b>: ova stranica je za prestanak primanja naših newslettera <b>zauvijek</b>. Ako želite promjeniti svoj e-mail, ili ako želite promjeniti newslettere koje želite primati , molimo <a href="[PREFERENCESURL]">osvježite svoje postavke</a>';
$strNoListsFound        = 'Nažalost, sa ovim e-mailom niste prijavljeni na niti jedan newsletter';
$strResubmit            = 'Ponovo pošalji E-mail';
$strUnsubscribeSubmit   = 'Odjavi me sa Izabranih Newslettera';
$strValuesMissing       = 'Slijedeća obavezna polja nedostaju';
$strConfirmInfo         = 'Hvala vam što ste potvrdili prijavu na naše newslettere. Newsletteri na koje ste se prijavili navedeni su ispod';
$strConfirmTitle        = 'PHPlist stranica potvrde članstva';
$strUserNotFound        = 'Korisnik nije nađen';
$strUserAlreadyInitialised = 'Nažalost, vaša lozinka vam je već poslana';
$strConfirmFailInfo     = 'Nažalost, vaš zahtjev za potvrdom nije prepoznat. Koristite punu web adresu kao što je navedno u e-mailu kojeg ste primili. Nekad se zna dogoditi da se ta web adresa prelomi u više redova.';
$strPreferHTMLEmail     = 'Preferiram primanje e-mailova u HTML obliku';
$strPreferTextEmail     = 'Preferiram primanje e-mailova u tekstualnom obliku';
$strPreferredFormat      = 'Preferirani oblik za e-mailove:';
$strText                 = 'Tekst';
$strHTML                = 'HTML';
$strPreferencesTitle    = 'Osvježite svoje postavke';
$strPreferencesInfo     = 'Molimo potvrdite da su informacije ispod točne i kliknite gumb "Update"';
$strUpdatePreferences   = 'Osvježi';
$strPreferencesEmailChanged = 'Vaša e-mail adresa je promjenjena. Molimo kliknite na link u e-mailu kojeg ćete primiti kako biste potvrdili vašu novu e-mail adresu';
$strYouAreBlacklisted = 'Vaša e-mail adresa je na našoj "Crnoj Listi", što znači da ste od nas zatražili da vam više ne šaljemo newslettere. <br/>
Kako biste ponovo počeli primati naše e-mailove, potrebna je ručna intervencija naših administratora. Kontaktirajte na i eksplicitno navedite da želite ponovo primati newslettere i mi ćemo
vas maknuti sa crne liste. ';
$strPreferencesNotificationSent = 'Dobiti ćete e-mail sa promjenama';
$strPreferencesUpdated = 'Hvala vam na vašem unosu. Osvježili smo vaše podatke.';
$strClickHere          = 'Kliknite ovdje';
$strThisLink           = 'ovaj link';
$strToUnsubscribe      = 'Ako ne želite više dobivati newslettere, ';
$strToUpdate           = 'Kako biste osvježili vaše postavke ili se odjavili posjetite';
$strSendHTML           = 'Pošalji HTML e-mail';
$strYes                = 'Da';
$strNo                 = 'Ne';
$strUnsubscribe        = 'Odjavi';
$strAllMailinglists    = 'Svi newsletteri';
$strAttachmentIntro     = 'Ova poruka sadrži privitak kojeg se može pregledati sa web preglednikom:';
$strLocation           = 'Lokacija';
$strFrequency           = 'Koliko često da vam šaljemo poruke?';
$strHourly             = 'Satno';
$strDaily               = 'Dnevno';
$strWeekly             = 'Tjedno';
$strMonthly             = 'Mjesečno';
$strChoosePassword      = 'Molimo izaberite lozinku';
$strConfirmPassword    = 'Potvrdite vašu lozinku';
$strEnterPassword       = 'Molimo unesite vašu lozinku';
$strForgotPassword     = 'Zaboravili ste lozinku';
$strPassword           = 'Lozinka';
$strPassword2           = 'Potvrdra lozinke';
$strPasswordsNoMatch    = 'Lozinke nisu jednake';
$strEmailsNoMatch     = 'E-mail adrese koje ste unijeli nisu jednake';
$strInvalidPassword     = 'Greška: pogrešna e-mail adresa ili lozinka';
$strPasswordSent        = 'Vaša lozinka vam je poslana e-mailom. Trebali biste je primiti u slijedećih nekoliko minuta';
$strPasswordRemindSubject = 'Vaša lozinka za naše newslettere';
$strPasswordRemindMessage = 'Vaša lozinka je ';
$strPasswordRemindInfo = 'Kako biste primili vašu lozinku e-mailom, molimo unesite vašu e-mail adresu i kliknite "'.$strForgotPassword.'" gumb.';
$strLogin               = 'Login';
$strLoginTitle          = 'Molimo unesite vašu e-mail adresu i lozinku';
$strLoginInfo           = 'Za ovu stranicu je potrebna lozinka. Molimo unesite vašu e-mail adresu i lozinku';
$strPersonalLocationInfo = '
  <p>Za ovu stranicu je potrebna osobna identifikacija koju možete naći u svakom e-mailu kojeg smo vam poslali.<br/>
  Ako ste kliknuli ovu lokaciju, i dobili ovu grešku, uvjerite se dali ste paste-ali(zalijepili) cijelu liniju linka u 
  adresno polje web preglednika. Zna se dogoditi da se lokacija razlomi u više linija.</p>
  <p>Ako neznate lokaciju, možete zatražiti e-mail koji će vam reći što je to.
  Molimo unesite vašu e-mail adresu i kliknite "Nastavi"
';
$strPersonalLocationSent = '<h1>Uspješno! Ubrzo biste trebali dobiti poruku sa vašom osobnom lokacijom</h1>';
$strUserExists   = '<br/>Koriste sa tom e-mail adresom već postoji, i naša evidencija sadrži drugačiju lozinku';
$strUserExistsExplanationStart = '<br/>Kako biste dobili svoju lozinku, kliknite ';
$strUserExistsExplanationLink = 'ovdje';
$strUserExistsExplanationEnd = ' kako biste otišli na stranicu gdje možete zatražiti vašu osobnu lokaciju';
$strForwardTitle = 'Proslijedi poruku Nekome';
$strForwardSubtitle = 'Proslijeđivanje poruke sa temom (Subject-om) ';
$strForwardEnterEmail = 'Molimo unesite važeću e-mail adresu kojoj će se proslijediti';
$strForwardSuccessInfo ='Poruka je proslijeđena';
$strForwardFailInfo = 'Proslijeđivanje poruke nije uspijelo';
$strForwardAlreadyDone = 'Ova poruka je već uspješno proslijeđena na tu e-mail adresu';
$strForwardFooter = 'Ova poruka vam je proslijeđena od [FORWARDEDBY].
  Niste automatski prijavljeni na ovaj newsletter.
  Kako biste se prijavili na ovaj newsletter otiđite na';
$strForward = 'Proslijedi';
$strFwd = 'Fwd'; # short version of forward for email subject
?>