<?php

# language dependent text used in the interface for users (not admin)
# Croatian translation by Mato Špekuljak mato.spekuljak@post.t-com.hr
# Updated by Vojan Jagić & Jernej Lekše (dragonticketing.com)
# Fixed by Petar Šlat (github.com/pekiZG)
# alternative coding iso-8859-2
# V. 11.03.06-01 /PHPlist 2.10.2
$strCharSet                     = 'UTF-8';
$strName                        = 'Ime i prezime';
$strAddress                     = 'Adresa';
$strEmail                       = 'e-mail adresa';
$strTown                        = 'Mjesto';
$strPostcode                    = 'Poštanski broj';
$strSubscribeInfo               = 'Popunite obrazac za prijavu na naše e-novosti.';
$strRequired                    = 'Obavezni podaci:';
$strSubscribeTitle              = 'Pretplata na naše e-novosti';
$strPleaseSelect                = 'Odaberite na koje se e-novosti želite pretplatiti.';
$strSubmit                      = 'Upis u mailing-liste';
$strNotAvailable                = 'Trenutno ne nudimo ni jednu mailing-listu.';
$strEnterName                   = 'Molimo vas da upišete vaše ime i prezime (ili nadimak).';
$strEnterEmail                  = 'Molimo vas da upišete vašu e-mail adresu';
$strInvalidHostInEmail          = 'Na žalost, e-mail adresu koju ste upisali ne možemo prihvatiti; molimo vas da još jedanput provjerite jeste li upisali ispravnu e-mail adresu.';
$strEnterList                   = 'Molimo Vas da izaberete mailing-listu u koju se želite upisati';
$strPleaseEnter                 = 'Nedostaje';

# the thanks message can contain placeholders
$strThanks                      = 'Hvala što ste se pretplatitli na naše e-novosti.';

# the EmailConfirmation message can contain placeholders
$strEmailConfirmation           = 'Adresa [e-mail] upisana je u našu bazu podataka. Sada će vam biti poslan zahtjev da pretplatu potvrdite. Da biste pretplatu potvrdili, molimo vas da kliknete na link u obavijesti.';
$strEmailFailed                 = 'Na žalost, zahtjev za potvrdu pretplate nije vam otišao. Pokušajte ponovno klikom na ikonu "Osvježi". Ako to nije pomoglo, možda je vaša e-mail adresa na popisu adresa koje ne mogu primati e-mailove iz sustava naših mailing-lista. Ako je tako, molimo vas da kontaktirate administratora.';
$strUnsubscribeTitle            = 'Odustajanje od pretplate';
$strUnsubscribeDone             = 'Pretplata na odabrane sadržaje je poništena. Obavijest o poništenju pretplate poslana vam je e-mailom .';
$strBack                        = 'Natrag';
$strUnsubscribeInfo             = 'Odustajanje od pretplate';
$strContinue                    = 'Nastavak';
$strUnsubscribeSelect           = 'Molimo Vas da odaberete e-novosti u koje više ne želite biti upisani';
$strAllLists                    = 'Sve liste';
$strNoLists                     = 'Nijedna lista';
$strUnsubscribeRequestForReason = 'Žao nam je što više niste zainteresirani za pretplatu na sadržaje naših e-novosti. Upisivanjem razloga vašeg odustajanja od pretplate možete pridonijeti da sadržaji koje nudimo postanu kvalitetniji:';
$strUnsubscribeFinalInfo        = '<br/><b>Molimo vas da uzmete u obzir</b>: preko ove web-stranice vaša pretplata na sadržaje naših mailing-lista poništava se <b>definitivno</b>. Želite li možda samo promijeniti vašu e-mail adresu ili sadržaje pretplate <a href="[PREFERENCESURL]">ovdje možete unijeti željene promjene</a> umjesto da poništite pretplatu';
$strNoListsFound                = 'Na žalost, ova e-mail adresa nije prisutna ni u jednoj pretplati na naše sadržaje.';
$strResubmit                    = 'Upišite ponovno e-mail adresu';
$strUnsubscribeSubmit           = 'Odustajanje od pretplate na odabrane sadržaje';
$strValuesMissing               = 'Nedostaju ili nisu aktualni ovi podaci';
$strConfirmInfo                 = 'Hvala što ste potvrdili upis u jednu ili više naših mailing-lista. Upisani ste u ove mailing-liste:';
$strConfirmTitle                = 'Web-stranica za potvrdu pretplate';
$strUserNotFound                = 'Ne postoji korisnik/korisnica s tim podacima';
$strUserAlreadyInitialised      = 'Na žalost, ovu zaporku ne možemo prihvatiti';
$strConfirmFailInfo             = 'Na žalost, vaš zahtjev za potvrdu pretplate nije prepoznat. Jeste li sigurni da ste upisali cijelu web-adresu koju smo vam poslali e-mailom kao link? U nekim programima za poštu web-adresa može biti prelomljena u dva ili više redaka.';
$strPreferHTMLEmail             = 'Želim primati e-mailove u formatu HTML.';
$strPreferTextEmail             = 'Želim primati e-mailove u formatu TEXT.';
$strPreferredFormat             = 'Izabrani format e-mailova:';
$strText                        = 'TEXT';
$strHTML                        = 'HTML';
$strPreferencesTitle            = 'Promjena podataka o pretplati';
$strPreferencesInfo             = 'Molimo vas da potvrdite promjene klikom na gumb "Promijeni".';
$strUpdatePreferences           = 'Promijeni';
$strPreferencesEmailChanged     = 'Promijenjena je e-mail adresa. Molimo vas da kliknete na link u e-mailu koji smo vam poslali kako biste potvrdili vašu novu e-mail adresu.';
$strYouAreBlacklisted           = 'Vaša e-mail adresa na popisu je adresa koje ne primaju e-mailove iz sustava naših mailing-lista, što znači da ste zatražili poništenje svih pretplata. <br/>Da biste mogli ponovno primati naše sadržaje, molimo vas da nas kontaktirate i zatražite da vam administrator obnovi pretplatu. On može vašu adresu ponovno aktivirati. ';
$strPreferencesNotificationSent = 'Koji su podaci ažurirani možete vidjeti iz obavijesti koja vam je upravo poslana e-mailom.';
$strPreferencesUpdated          = 'Zahvaljujemo na ažuriranju podataka. Podaci su ažurirani.';
$strClickHere                   = 'Kliknite ovdje';
$strThisLink                    = 'ovaj link';
$strToUnsubscribe               = 'Ako više ne želite primati naše sadržaje';
$strToUpdate                    = 'Ako želite promijeniti podatke o vašoj pretplati ili poništiti vašu pretplatu molimo vas da otvorite web-stranicu';
$strSendHTML                    = 'e-mail u formatu HTML';
$strYes                         = 'Da';
$strNo                          = 'Ne';
$strUnsubscribe                 = 'Poništavam pretplatu';
$strAllMailinglists             = 'Sve liste';
$strAttachmentIntro             = 'Ovaj e-mail sadrži linkove koji koji se mogu vidjeti tj. aktivirati web-tražilicom (browserom):';
$strLocation                    = 'Lokacija';
$strFrequency                   = 'U kojim vremenskim razmacima želite primati e-mailove s našim sadržajima?';
$strHourly                      = 'Svaki sat';
$strDaily                       = 'Svaki dan';
$strWeekly                      = 'Jedanput tjedno';
$strMonthly                     = 'Jedanput mjesečno';
$strChoosePassword              = 'Molimo vas da odaberete zaporku';
$strConfirmPassword             = 'Potvrda zaporke';
$strConfirmPassword             = 'Potvrda zaporke';
$strEnterPassword               = 'Molimo vas da upišete zaporku';
$strForgotPassword              = 'Zaboravio/Zaboravila sam zaporku';
$strPassword                    = 'Zaporka';
$strPassword2                   = 'Potvrda zaporke';
$strPasswordsNoMatch            = 'Upisane zaporke nisu istovjetne.';
$strEmailsNoMatch               = 'Upisane e-mail adrese nisu istovjetne.';
$strInvalidPassword             = 'Pogrešna e-mail adresa ili zaporka';
$strPasswordSent                = 'Zaporka je poslana e-mailom. Trebali biste je dobiti za najviše nekoliko minuta.';
$strPasswordRemindSubject       = 'Zaporka za naše mailing-liste';
$strPasswordRemindMessage       = 'Vaša je zaporka:';
$strPasswordRemindInfo          = 'Da biste dobili zaporku e-mailom, molimo vas da upišete vašu e-mail adresu i kliknete na "'.$strForgotPassword.'" gumb.';
$strLogin                       = 'Prijava';
$strLoginTitle                  = 'Molimo vas da upišete e-mail adresu i zaporku';
$strLoginInfo                   = 'Ova web-stranica zahtijeva zaporku. Molimo vas da upišete e-mail adresu i zaporku';
$strPersonalLocationInfo        = '<p>Ova stranica zahtijeva unošenje u web-tražilicu (browser) web-adrese s vašom identifikacijskom oznakom. Web-adresa s vašom identifikacijskom oznakom nalazi se u svakom e-mailu koji od nas primite.<br/>Ako vam nakon unosa u web-tražilicu (browser) adrese iz našeg e-maila bude javljena pogreška, provjerite jeste li unijeli cijeli redak u rubriku za web-adresu na web-tražilici (browseru). Katkad je web-adresa primljena preko nekih programa za poštu prelomljena u dva ili više redaka pa ste možda u web-tražilicu (browser) unijeli samo dio adrese.</p><p>Ako ne znate web-adresu s Vašom identifikacijskom oznakom korisnika/korisnice naših mailing-lista možete od nas zatražiti E-mail s takvom adresom. Unesite Vašu E-mail adresu u rubriku za adresu i kliknite na gumb "Nastavak"';
$strPersonalLocationSent        = '<h1>Uspjeli ste! Obavijest s vašom identifikacijskom oznakom poslana je na vašu e-mail adresu. </h1>';
$strUserExists                  = '<br/>Korisnik s upisanom e-mail adresom registriran je pod drugom zaporkom';
$strUserExistsExplanationStart  = '<br/>Želite li dobiti vašu zaporku kliknite ';
$strUserExistsExplanationLink   = 'ovdje';
$strUserExistsExplanationEnd    = 'da biste došli na web-stranicu na kojoj možete zatražiti vašu lokaciju';
$strForwardTitle                = 'Proslijedi e-mail drugoj osobi';
$strForwardSubtitle             = 'Proslijedi e-mail s naznakom predmeta ';
$strForwardEnterEmail           = 'Upišite e-mail adresu na koju želite proslijediti e-mail';
$strForwardSuccessInfo          = 'e-mail je poslan na drugu adresu';
$strForwardFailInfo             = 'e-mail nije poslan na drugu e-mail adresu';
$strForwardAlreadyDone          = 'Ovaj e-mail već je poslan na drugu e-mail adresu';
$strForwardFooter               = 'Ovaj ste e-mail dobili od [FORWARDEDBY]. Vi nemate pretplatu na takve sadržaje. Želite li se pretplatiti na takve sadržaje idite na';
$strForward                     = 'Forward';
$strFwd                         = 'Fwd'; # short version of forward for email subject
