<?php

# language dependent text used in the interface for users (not admin)

$strCharSet             = 'UTF-8';
$strLancode             = 'cs'; ## two letter iso code
$strLandir              = 'ltr'; ## language direction (ltr or rtl)
$strName                = 'Jméno';
$strAddress             = 'Adresa';
$strEmail               = 'Email';
$strTown                = 'Město';
$strPostcode            = 'PSČ';
$strSubscribeInfo       = '<h3>Přihlašte se k našemu newsletteru</h3>';
$strRequired            = 'povinná pole jsou označena červeně';
$strSubscribeTitle      = 'Přihlašte se k našemu newsletteru';
$strPleaseSelect        = 'Prosím vyberte newsletter, ke kterému se chcete přihlásit';
$strSubmit              = 'Přihlašte se k vybranému newsletteru';
$strNotAvailable        = 'Žádný newsletter není dostupný';
$strEnterName           = 'Zadejte Vaše jméno';
$strEnterEmail          = 'Zadejte Váš email';
$strConfirmEmail        = 'Potvrdte Váš email';
$strInvalidHostInEmail  = 'Email je nedoručitelný, zkontrolujte prosím, zda je napsán správně';
$strEnterList           = 'Vyberte newsletter, ke kterému se chcete přihlásit';
$strPleaseEnter         = 'Zadejte vaše';
# the thanks message can contain placeholders
#$strThanks              = 'Vážený/á [FIRST NAME], <br/>Děkujeme za přihlášení do naší databáze.';
$strThanks              = 'Děkujeme za přihlášení k naší databázi.';
# the EmailConfirmation message can contain placeholders
#$strEmailConfirmation   = 'Váš email [email] byl přidán do našeho systému. V krátké době obdržíte emailem žádost o potvrzení přihlášení k Vámi zvoleným newsletterům.';
$strEmailConfirmation   = 'Váš email byl přidán do našeho systému. Obdržíte email s požadavkem o potvrzení vašeho přihlášení. Kliknutím na odkaz potvrdíte přihlášení.';
$strEmailFailed          = 'Email s požadavkem potvrzení registrace se nepodařilo odeslat. Klikněte, prosím, na tlačítko "Obnovit" ke zopakování odeslání. Pokud problém přetrvává, kontaktujte prosím administrátora.';
$strUnsubscribeTitle    = 'Odhlášení z naší databáze';
$strUnsubscribeDone     = 'Byli jste úspěšně odhlášeni z naší databáze, obdržíte email s žádostí o potvrzení odhlášení.';
$strUnsubscribedNoConfirm = 'Byli jste úspěšně odhlášeni z naší databáze';
$strBack                = 'Zpět';
$strUnsubscribeInfo     = 'Odhlášit z naší databáze';
$strContinue            = 'Pokračovat';
$strUnsubscribeSelect   = 'Vyberte, databáze ze kterých se chcete odhlásit';
$strAllLists            = 'Všechny databáze';
$strNoLists             = 'Žádná';
$strUnsubscribeRequestForReason = 'Je nám líto, že nemáte zájem nadále odebírat náš newsletter. Pokud nám chcete pomoci zlepšit naše služby, sdělte nám prosím důvod vašeho odhlášení:';
$strUnsubscribeFinalInfo = '<br/><b>Pozor</b>: tato stránka slouží ke zrušení <b>navždy</b> odběru našeho newsletteru. Pokud chcete pouze změnit Vaši emailovou adresou nebo změnit informace <a href="[PREFERENCESURL]">změňte Vaše nastavení</a>';
$strNoListsFound        = 'Tímto emailem nejste příhlášen do žádné naší databáze';
$strResubmit            = 'Znovu potvrdit';
$strUnsubscribeSubmit   = 'Odhlášení z vybraných databází';
$strValuesMissing       = 'Následující vyžadovaná pole nejsou vyplněna';
$strConfirmInfo         = 'Děkujeme za potvrzení přihlášení k našim newsletterům. Seznam Newsletterů, k jejichž odběru jste se přihlásili';
$strAlreadyConfirmed    = 'Vaše potvrzení jsme již obdrželi.';
$strConfirmTitle        = 'Potvrzovací stránka';
$strUserNotFound        = 'Uživatel nenalezen';
$strUserAlreadyInitialised = 'Vaše heslo bylo již nastaveno';
$strConfirmFailInfo     = 'Litujeteme, ale při potvrzení došlo k chybě. Ujistětete se zda jste vyplnili úplnou webovou adresu, kterou jste obdrželi v emailu. Občas bývá adresa zalomena na několik řádků.';
$strPreferHTMLEmail     = 'Preferuji zasílání mailů v HTML';
$strPreferTextEmail     = 'Preferuju zasílání mailů v prostém textu';
$strPreferredFormat      = 'Preferovaný formát mailů:';
$strText                 = 'Text';
$strHTML                = 'HTML';
$strPreferencesTitle    = 'Aktulizujte své vlastnosti';
$strPreferencesInfo     = 'Potvrdte, prosím, že uvedená data jsou správná a klikněte na tlačítko "Aktulizovat"';
$strUpdatePreferences   = 'Aktulizovat';
$strPreferencesEmailChanged = 'Váš emailová adresa byla změněna. Klikněte prosím na odkaz v emailu, který obdržíte. Tím dojde k potvrzení změny emailové adresy';
$strYouAreBlacklisted = 'Na Vaší emailovou adresu nejsou zasílány žádné newslettery, protože jste požadoval zrušení zasílání newsletterů.<br/>
Pokud chcete opět dostávat newslettery, je třeba ručního zásahu administrátora.
Prosím, kontaktujte nás s požadavkem, že chcete opětovně dostávat newslettery. ';
$strPreferencesNotificationSent = 'Obdržíte email s Vašimi změnami';
$strPreferencesUpdated = 'Informace byly aktualizovány. Děkujeme.';
$strClickHere          = 'Klikněte zde';
$strThisLink           = 'Tento odkaz';
$strToUnsubscribe      = 'Jestli nechtete dostávat žadné newslettery, ';
$strToUpdate           = 'K aktulizovaní vašich vlastností a odhlášení naštivte';
$strSendHTML           = 'Posílat HTML';
$strYes                = 'Ano';
$strNo                 = 'Ne';
$strUnsubscribe        = 'Odhlásit';
$strAllMailinglists    = 'Všechny newslettery';
$strAttachmentIntro     = 'Tato zpráva obsahuje přílohy, které mohou být zobrazeny ve webovém prohlížeči:';
$strLocation           = 'Umístění';
$strFrequency           = 'Jak často Vám zasíláme zprávy';
$strHourly             = 'Každou hodinu';
$strDaily               = 'Denně';
$strWeekly             = 'Týdně';
$strMonthly             = 'Měsíčně';
$strChoosePassword      = 'Zvolte si heslo';
$strConfirmPassword    = 'Potvrdte heslo';
$strEnterPassword       = 'Zadejte heslo';
$strForgotPassword     = 'Zapomenuté heslo';
$strForgotPasswordEmailBody = '
    Vážený správce Newsletteru,

    Zapomněl jesm heslo pro phpList mailinglist systém.
    Můžete jej prosím resetovat a zaslat mi jej?

    Děkuji
';

$strPassword           = 'Heslo';
$strPassword2           = 'Potvrdte heslo';
$strPasswordsNoMatch    = 'Hesla nejsou stejná';
$strEmailsNoMatch     = 'Email, který jste zadal nesouhlasí';
$strEmailNotValid  = 'Emailová adresa není platná';
$strInvalidPassword     = 'Chyba: špatný email nebo heslo';
$strPasswordSent        = 'Vaše heslo bylo zasláno na Váš email. Měli byste jej obdržet během někoika minut';
$strPasswordRemindSubject = 'Vaše heslo pro naše newslettery';
$strPasswordRemindMessage = 'Vaše heslo je ';
$strPasswordRemindInfo = 'K obdržení hesla emailem zadejte váš email a klikněte na "'.$strForgotPassword.'".';
$strLogin               = 'Přihlásit';
$strLoginTitle          = 'Prosím zadejte váš email a heslo';
$strLoginInfo           = 'Tato stránka vyžaduje Vaše heslo. Prosím zadejte Váš email a vaše heslo';
$strPersonalLocationInfo = '
<p>Tato stránka vyžaduje osobní identifikaci, kterou najdete v každém emailu, který jste od nás obdržel.<br/>
  Pokud jste klikli na tento odkaz a přesto čtete toto hlášění, přesvědčte se prosím, že jste do prolhlížeče vložili celý odkaz. Občas je odkaz zalomen na několik řádků.</p>
  <p>Pokud odkaz neznáte, vyžádejte si jej vložením Vaší emailové adresy a stiskem tlačítka "Pokračovat</p>"
';
$strPersonalLocationSent = '<h3>Úspěch! V nejbližší době obdržíte email s Vaším osobním umístěním</h3>';
$strUserExists   = 'Uživatel s tímto emailem již existuje a má jiné heslo';
$strUserExistsExplanationStart = '<br/>Pro získání svého hesla klikněte ';
$strUserExistsExplanationLink = 'Zde';
$strUserExistsExplanationEnd = ' Přejdětě na stránku kde obdržíte vaše osobní umístění';
$strExplainBlacklist = 'Email, který jste zadal je naším systémem blokován pro odesílání emailů na tuto adresu.';

$strUserExistsResubscribe = 'Tento email je již registrován';
$strUserExistsResubscribeExplanation = 'Aktualizujte svoje údaje v <a href="%s">Nastavení</a>.';


$strForwardTitle = 'Přeposlat zprávu';
$strForwardSubtitle = 'Přeposlat zprávu s předmětem ';
$strForwardEnterEmail = 'Zadejte platný email, na který chcete zprávu přeposlat';
$strForwardInvalidEmail = 'Nesprávný email';
$strForwardBlacklistedEmail = 'Příjemce si nepřeje zasílat emaily z tohoto systému.';
$strForwardEnterEmails = 'Zadejte prosím v tomto poli maximálně % platných emailových adres (každou na samostatný řádek), kterým bude newsletter přeposlán.';
$strForwardPersonalNote = 'Můžete zadat jednoduchou textovou zprávu (z max. % znaků) která bude vložena na začátku mailu s newsletterem';
$strForwardSuccessInfo ='Zpráva byla přeposlána';
$strForwardFailInfo = 'Odeslání zprávy selhalo';
$strForwardAlreadyDone = 'Tato zpráva již byla úspěšně předána na tuto emailovou adresu';
$strForwardCountReached = 'Dosažen maximální počet přeposlání';
$strForwardNoteLimitReached = 'Dosažena maximální délka vzkazu přeposlílaném';
$strForwardFooter = 'Tato zpráva Vám byla přeposlána [FORWARDEDBY].
  Nebyl jste automaticky přihlášen do tohoto newsletteru.
  Pokud chcete přihlásit přejděte na';
$strForward = 'Přeposlat';
$strFwd = 'Fwd'; # short version of forward for email subject
