<?php

# language dependent text used in the interface for users (not admin)

$strCharSet             = 'UTF-8';
$strName                = 'Jméno';
$strAddress             = 'Adresa';
$strEmail               = 'Email';
$strTown                = 'Město';
$strPostcode            = 'PSČ';
$strSubscribeInfo       = '<h1>Přihlašte se k našemu newsletteru</h1>';
$strRequired            = 'Požadovaná pole jsou označena červeně';
$strSubscribeTitle      = 'Přihlašte se k našemu newsletteru';
$strPleaseSelect        = 'Prosím vyberte newsletter ke kterému se chcete přihlásit';
$strSubmit              = 'Přihlašte se k vybranému newsletteru';
$strNotAvailable        = 'Omlouváme se, žádný newsletter není dostupný';
$strEnterName           = 'Prosím zadejte Vaše jméno';
$strEnterEmail          = 'Prosím zadejte Váš email';
$strConfirmEmail        = 'Potvrdte váš email';
$strInvalidHostInEmail  = 'Omlouváme se, ale email je nedoručitelný, zkontrolujte zda je napsán správně';
$strEnterList           = 'Prosím vyberte newsletter, ke kterému se chcete přihlásit';
$strPleaseEnter         = 'Prosím zadejte vaše';
# the thanks message can contain placeholders
#$strThanks              = 'Vážený/á [FIRST NAME], <br/>Dekujeme za prihlášení do naší databáze.';
$strThanks              = 'Děkujeme za přihlášení k naší databázi.';
# the EmailConfirmation message can contain placeholders
#$strEmailConfirmation   = 'Váš email [email] byl přidán do našeho systému.';
$strEmailConfirmation   = 'Váš email byl přidán do našeho systému.';
$strEmailFailed          = 'Litujeteme ale registraci potvrzující email se nepodařilo odeslat.';
$strUnsubscribeTitle    = 'Odhlášení z naší databáze';
$strUnsubscribeDone     = 'Byly jste úspěšně vymazáni z naší databáze.';
$strBack                = 'Zpátky';
$strUnsubscribeInfo     = 'Odhlášení z databáze';
$strContinue            = 'Pokračovat';
$strUnsubscribeSelect   = 'Prosím vyberte databáze ze kterých se chcete odhlásit';
$strAllLists            = 'Všechny databáze';
$strNoLists             = 'Žádná z nich';
$strUnsubscribeRequestForReason = 'Je nám líto, že nemáte zájem o naše informace. Pokud nám chcete pomoci zlepšit naše služby, sdělte nám prosím důvod vašeho odhlášení:';
$strUnsubscribeFinalInfo = '<br/><b>Pozor</b>: potvrzením tlačítka "Odhlásit" zrušíte odběr informaci <b>navždy</b>. Pokud chcete pouze změnit Vaši emailovou adresou nebo změnit informace využijte prosím <a href="[PREFERENCESURL]">tento odkaz</a> instead';
$strNoListsFound        = 'Promiňte, nejste příhlášen do žádné naší databáze s tímto emailem';
$strResubmit            = 'Znovu potvrdit emailovou adresu';
$strUnsubscribeSubmit   = 'Odhlášení z uvedených databází';
$strValuesMissing       = 'Chybějí vyžadovaná pole';
$strConfirmInfo         = 'Děkujeme za potvrzení přihlášení k našim Newsletterům. Newslettery ke kterým jste se přihlásili k odběru jsou uvedeny zde';
$strConfirmTitle        = 'Potvrzovací stránka';
$strUserNotFound        = 'Uživatel nenalezen';
$strUserAlreadyInitialised = 'Omlouváme se, Vaše heslo bylo již nastaveno';
$strConfirmFailInfo     = 'Litujeteme, ale při potvrzení došlo k chybě. Ujistětete se zda jste vyplnili plnou webovou adresu, kterou jste obdrželi v emailu.';
$strPreferHTMLEmail     = 'Preferuju zasílání mailů v HTML';
$strPreferTextEmail     = 'Preferuju zasílání mailů v textu';
$strPreferredFormat      = 'Preferovaný formát mailů:';
$strText                 = 'Text';
$strHTML                = 'HTML';
$strPreferencesTitle    = 'Aktulizujte své vlastnosti';
$strPreferencesInfo     = 'Prosím potvrdte, že uvedená data jsou správné a klikněte na "Aktulizovat"';
$strUpdatePreferences   = 'Aktulizovat';
$strPreferencesEmailChanged = 'Váš email se změnil. Navštivte prosím odkaz v emailu kde obdržíte Vaší novou e-mailovou adresu';
$strYouAreBlacklisted = 'Vaše emailová adresa je na blokována, protože bylo požadováno zrušení zasílání emailů <br/>
Kontaktujte administrátora tohoto webu, který na Vaši žádost obnoví zasílání ';
$strPreferencesNotificationSent = 'Obdržíte email s Vašimi změnami';
$strPreferencesUpdated = 'Děkujeme za Vaše informace. Aktulizovali jsme je.';
$strClickHere          = 'Klikněte zde';
$strThisLink           = 'Tento odkaz';
$strToUnsubscribe      = 'Jestli nechtete dostávat žadné newslettery, ';
$strToUpdate           = 'K aktulizovaní vašich vlastností a odhlášení naštivte';
$strSendHTML           = 'Posílat HTML';
$strYes                = 'Ano';
$strNo                 = 'Ne';
$strUnsubscribe        = 'Odhlásit';
$strAllMailinglists    = 'Všechny newslettery';
$strAttachmentIntro     = 'Tato zpráva obsahuje přílohy, které mohou být zobrazeny v prohlížeči:';
$strLocation           = 'Umístění';
$strFrequency           = 'Jak často Vám zasíláme zprávy';
$strHourly             = 'Každou hodinu';
$strDaily               = 'Denně';
$strWeekly             = 'Týdně';
$strMonthly             = 'Měsíčně';
$strChoosePassword      = 'Prosím zvolte si heslo';
$strConfirmPassword    = 'Potvrdte heslo';
$strEnterPassword       = 'Prosím zadejte heslo';
$strForgotPassword     = 'Zapomenuté heslo';
$strPassword           = 'Heslo';
$strPassword2           = 'Potvrdte heslo';
$strPasswordsNoMatch    = 'Hesla nejsou stejná';
$strEmailsNoMatch     = 'Email, který jste zadal nesouhlasí';
$strInvalidPassword     = 'Chyba: špatný mail nebo heslo';
$strPasswordSent        = 'Vaše heslo bylo zasláno na Váš email.';
$strPasswordRemindSubject = 'Vaše heslo pro naše newslettery';
$strPasswordRemindMessage = 'Vaše heslo je ';
$strPasswordRemindInfo = 'K obdržení hesla emailem zadejte váš email a klikněte na "'.$strForgotPassword.'".';
$strLogin               = 'Přihlásit';
$strLoginTitle          = 'Prosím zadejte váš email a heslo';
$strLoginInfo           = 'Tato stránka vyžaduje Vaše heslo. Prosím zadejte Váš email a vaše heslo';
$strPersonalLocationInfo = '
<p>Tato stránka vyžaduje osobní identifikaci, kterou najdete v každém emailu, který jsme Vám zaslali.<br/>
  Pokud jste využili odkaz osobní identifikace a přesto čtete toto hlášění, přesvědčte se prosím, že odkaz je na jednom řádku, nezalomen.</p>
  <p>Pokud odkaz osobní identifikace  nemáte, vyžádejte si ho vložením Vaší emailové adresy a stiskněte tlačítko "Pokračovat"
';
$strPersonalLocationSent = '<h1>Úspěšné! V nejbližší době obdržíte Vaše osobní umístění</h1>';
$strUserExists   = '<br/>Uživatel s tímto emailem již existuje a v záznamech má jiné heslo';
$strUserExistsExplanationStart = '<br/>Pro získání svého hesla klikněte ';
$strUserExistsExplanationLink = 'Zde';
$strUserExistsExplanationEnd = ' Přejdětě na stránku kde obdržíte vaše osobní umístění';
$strExplainBlacklist = 'Email, který jste zadal je naším systémem blokován pro odesílání emailů na tuto adresu.';
$strForwardTitle = 'Přeposlat zprávu někomu';
$strForwardSubtitle = 'Přeposlat zprávu s předmětem ';
$strForwardEnterEmail = 'Prosím zadejte email na který chcete zprávu přeposlat';
$strForwardInvalidEmail = 'Toto není správný email';
$strForwardBlacklistedEmail = 'Příjemce si nepřeje zasílat emaily z tohoto systému.';
$strForwardEnterEmails = 'Zadejte prosím maximálně % platných emailových adres k předání v tomto poli, jeden na řádek';
$strForwardPersonalNote = 'Můžete zadat jednoduchou textovou zprávu (z max. % znaků) která bude předána emailem';
$strForwardSuccessInfo ='Zpráva byla přeposlána';
$strForwardFailInfo = 'Zpráva nebyla přeposlána';
$strForwardAlreadyDone = 'Tato zpráva již byla úspěšně předána na tuto emailovou adresu';
$strForwardCountReached = 'Dosažen maximální počet přeposlání';
$strForwardNoteLimitReached = 'Dosažena maximální délka osobní poznámky';
$strForwardFooter = 'Tato zpráva Vám byla přeposlána [FORWARDEDBY].
  Nebyl jste automaticky přihlášen do tohoto newsletteru.
  Pokud chcete přihlásit přejděte na';
$strForward = 'Přeposlat';
$strFwd = 'Fwd'; # short version of forward for email subject


?>
