<?php
# language dependent text used in the interface for users (not admin)
# translation by Gijsbert Rochat, updated by Jean-Luc Picard and Alain Rihs

$strCharSet             = 'UTF-8';
$strLancode             = 'fr';
$strLandir              = 'ltr';
$strName                = 'Nom';
$strAddress             = 'Adresse';
$strEmail               = 'Adresse électronique';
$strTown                = 'Ville';
$strPostcode            = 'Code postal';
$strSubscribeInfo       = '<h3>S’abonner à une ou plusieurs listes</h3>';
$strRequired            = 'Champ requis indiqué en rouge';
$strSubscribeTitle      = 'S’abonner à nos listes';
$strPleaseSelect        = 'Veuillez sélectionner les listes auxquelles vous désirez vous abonner ';
$strSubmit              = 'S’abonner aux listes sélectionnées';
$strNotAvailable        = 'Désolé, aucune liste n’est disponible actuellement.';
$strEnterName           = 'Entrez votre nom';
$strEnterEmail          = 'Entrez votre adresse électronique';
$strConfirmEmail        = 'Confirmez votre adresse électronique';
$strInvalidHostInEmail  = 'Désolé, aucun message ne peut être envoyé à ce domaine. Veuillez vérifier que vous avez correctement entré votre adresse électronique';
$strEnterList           = 'Veuillez sélectionner une liste à laquelle vous abonner :';
$strPleaseEnter         = 'Veuillez entrer votre';
$strCheckbox            = 'Le champ suivant est obligatoire: ';
# the thanks message can contain placeholders
#$strThanks             = 'Dear [FIRST NAME], <br/>Thank you for subscribing to our lists.';
$strThanks              = 'Merci de vous être abonné·e à nos listes.';
# the EmailConfirmation message can contain placeholders
#
#$strEmailConfirmation  = 'Your email [email] has been added to our system. You will be e-mailed shortly with confirmation of the lists you have subscribed to.';
$strEmailConfirmation   = 'Votre adresse électronique [email] a été enregistrée dans notre plateforme. Vous allez recevoir un message vous demandant de confirmer votre abonnement. Il vous faudra confirmer votre abonnement en cliquant sur le lien contenu dans le message.';
$strEmailFailed			= 'Désolé, l’envoi du message de confirmation a échoué. Veuillez réactualiser la page pour réessayer.';
$strUnsubscribeTitle    = 'Se désabonner de nos listes';
$strUnsubscribeDone     = 'Vous avez été désabonné·e des listes choisies. Vous recevrez un message de confirmation.';
$strUnsubscribedNoConfirm	= 'Vous avez été désabonné de ce système.';
$strBack                = 'Retour';
$strUnsubscribeInfo     = 'Se désabonner d’une ou de plusieurs de nos listes';
$strContinue            = 'Continuer';
$strUnsubscribeSelect   = 'Veuillez sélectionner les listes auxquelles vous désirez vous désabonner';
$strAllLists            = 'Toutes les listes';
$strNoLists             = 'Aucune liste';
$strUnsubscribeRequestForReason = 'Nous sommes désolés de constater que vous ne souhaitiez plus recevoir nos messages. Afin de nous aider à améliorer nos services, pourriez-vous nous en préciser les raisons ? :';
$strUnsubscribeFinalInfo = '<br/><b>Attention :</b> Cette page est une page de désinscription <b>définitive</b> de nos listes. Si vous désirez changer votre adresse électronique ou modifier les listes auxquelles vous êtes abonné·e, veuillez utiliser le lien <a href="[PREFERENCESURL]">pour mettre à jour votre préférences</a> à la place.';
$strNoListsFound        = 'Désolé, vous n’êtes inscrit·e à aucune liste avec cette adresse électronique.';
$strResubmit            = 'Soumettre à nouveau';
$strUnsubscribeSubmit   = 'Se désabonner des listes sélectionnées';
$strValuesMissing       = 'Les entrées requises suivantes manquent :';
$strConfirmInfo         = 'Merci de vous être abonné·e à nos listes. Les listes auxquelles vous vous êtes abonné·e sont affichées ci-dessous :';
$strAlreadyConfirmed    = 'Nous avons déjà reçu précédement votre confirmation.';
$strConfirmTitle        = 'Page de confirmation pour la plateforme phpList';
$strUserNotFound        = 'Destinataire introuvable';
$strUserAlreadyInitialised = 'Désolé, votre mot de passe a déjà été défini';
$strConfirmFailInfo     = 'Désolé, votre demande de confirmation n’a pas été reconnu. Veuillez vérifier que vous utilisez bien l’adresse complète du lien contenu dans le message que vous avez reçu. Parfois, ce lien tient sur plusieurs lignes.';
$strPreferHTMLEmail     = 'Je préfère recevoir les messages en mode HTML.';
$strPreferTextEmail     = 'Je préfère recevoir les messages en mode texte brut';
$strPreferredFormat     = 'Format préféré pour les messages :';
$strText                = 'Texte brut';
$strHTML                = 'HTML';
$strPreferencesTitle    = 'Mettre à jour vos préférences';
$strPreferencesInfo     = 'Vérifiez que les informations ci-dessous sont correctes puis cliquez sur le bouton : « mettre à jour »';
$strUpdatePreferences   = 'Mettre à jour';
$strPreferencesEmailChanged = 'Votre adresse électronique a changé. Veuillez cliquer sur le lien dans le message que vous allez recevoir pour confimer ce changement.';
$strYouAreBlacklisted = 'Votre adresse électronique est dans notre liste d’envois interdits, vous avez demandé de ne plus recevoir de messages de notre part.<br/>
Pour recevoir à nouveau nos courriels, une intervention manuelle de notre administrateur est nécessaire. Contactez le et indiquez lui explicitément que vous souhaitez recevoir à nouveau nos messages.';
$strPreferencesNotificationSent = 'Vous allez recevoir un message avec vos modifications.';
$strPreferencesUpdated = 'Vos informations ont été mises à jour.';
$strClickHere          = 'Cliquez ici';
$strThisLink           = 'ce lien';
$strToUnsubscribe      = 'Pour vous désabonner de cette liste, visitez :';
$strToUpdate           = 'Pour mettre vos préférences à jour ou vous désabonner, visitez :';
$strSendHTML           = 'Envoyer le message au format HTML';
$strYes                = 'Oui';
$strNo                 = 'Non';
$strUnsubscribe        = 'Se désabonner';
$strAllMailinglists    = 'Toutes les Listes';
$strAttachmentIntro  = 'Ce message contient des pièces jointes qui peuvent être ouvertes avec un navigateur :';
$strLocation    = 'Localisation';
$strFrequency    = 'Fréquence d’envoi de nos messages';
$strHourly    = 'Chaque heure';
$strDaily    = 'Journalière';
$strWeekly    = 'Hebdomadaire';
$strMonthly    = 'Mensuelle';
$strChoosePassword   = 'Veuillez choisir un mot de passe';
$strConfirmPassword   = 'Confirmez votre mot de passe';
$strEnterPassword  = 'Veuillez entrer votre mot de passe';
$strForgotPassword  = 'Mot de passe oublié';
$strForgotPasswordEmailBody = '
    Cher gestionnaire de la liste de diffusion

    J’ai oublié mon mot de passe pour cette plateforme phpList.
    Pouvez-vous le réinitialiser et me transmettre le nouveau mot de passe ?

    Merci
'; 
$strPassword    = 'Mot de passe';
$strPassword2    = 'Confirmation du mot de passe';
$strPasswordsNoMatch   = 'Les mots de passe ne sont pas identiques';
$strEmailsNoMatch     = 'Les adresses électroniques ne correspondent pas';
$strEmailNotValid  = 'L’adresse électronique n’est pas valide';
$strInvalidPassword  = 'Erreur : adresse électronique ou mot de passe invalide';
$strPasswordSent   = 'Le mot de passe vient de vous être envoyé. Vous devriez le recevoir d’ici quelques minutes';
$strPasswordRemindSubject = 'Votre mot de passe pour nos listes d’informations';
$strPasswordRemindMessage = 'Votre mot de passe est ';
$strPasswordRemindInfo = 'Pour recevoir votre mot de passe, veuillez entrer votre adresse électronique et cliquez sur le bouton « '.$strForgotPassword.' ».';
$strLogin    = 'Connexion';
$strLoginTitle     = 'Veuillez saisir votre adresse électronique et votre mot de passe';
$strLoginInfo    = 'Cette page nécessite un mot de passe. Veuillez saisir votre adresse électronique et votre mot de passe';
$strPersonalLocationInfo = '<p>Cette page nécessite une authentification personnalisée qui peut être
 trouvée sur chaque message précédemment envoyé.</p>
 <p>Si vous avez cliqué à partir d’un lien pour obtenir cette page et que vous obteniez cette erreur, veuillez copier l’adresse complète du lien, même si celle-ci tient sur plusieurs lignes, et la coller ensuite dans le champ correspondant de votre navigateur.</p>
<p>Si vous ne connaissez pas sa localisation, vous pouvez demander un courriel qui vous la fera
 parvenir. Veuillez entrer votre adresse électronique dans le champ et cliquez sur Continuer';
$strPersonalLocationSent = '<h1>Bravo ! Vous devriez recevoir rapidement un courriel avec vos indications personnalisées</h1>';
$strUserExists   = 'Un destinataire avec cette adresse électronique existe déja, mais le mot de passe ne correspond pas';
$strUserExistsExplanationStart = 'Afin d’obtenir votre mot de passe cliquez ';
$strUserExistsExplanationLink = 'ici';
$strUserExistsExplanationEnd = ' pour aller à la page ou vous trouverez vos informations personelles';
$strExplainBlacklist = 'L’adresse que vous venez d’indiquer sera enregistrée dans notre base afin de ne plus vous envoyer de messages.';

$strUserExistsResubscribe = 'Un abonné avec cette adresse existe déjà';
$strUserExistsResubscribeExplanation = 'Veuillez aller sur la <a href="%s">page des préférences</a> afin de mettre à jour vos données.';


$strForwardTitle = 'Transférer le message';
$strForwardSubtitle = 'Faire suivre le message ayant pour sujet ';
$strForwardEnterEmail = 'Veuillez saisir une adresse électronique valide auquel le message sera transféré';
$strForwardInvalidEmail = '%s n’est pas une adresse électronique valide.';
$strForwardBlacklistedEmail = 'Le destinataire a demandé de ne pas recevoir de messages en provenance du système.';
$strForwardEnterEmails = 'Veuillez saisir dans cette zone un maximum de %s adresse(s) électronique(s), une adresse par ligne';
$strForwardPersonalNote = 'Vous pouvez ajouter un message (d’un maximum de %d caractères) qui sera ajouté au message transféré';
$strForwardSuccessInfo ='Le message a été transféré.';
$strForwardFailInfo = 'Le transfert du message a échoué.';
$strForwardAlreadyDone = 'Ce message a déjà été transféré avec succès à cettre adresse électronique';
$strForwardCountReached = 'Le nombre de transferts maximum autorisés a été atteint.';
$strForwardNoteLimitReached = 'La taille limite de la note personnelle a été atteinte';
$strForwardFooter = 'Ce message vous a été transféré par [FORWARDEDBY].
  Vous n’avez pas été inscrit automatiquement sur cette liste de diffusion.
  pour vous y inscrire allez à :';
$strForward = 'Faire Suivre';
$strFwd = 'Tr'; # short version of forward for email subject
$strContactAdmin = 'Contacter l’administrateur';
?>
