<?php

# language dependent text used in the interface for users (not admin)

$strName                = 'Name';
$strAddress             = 'Addresse';
$strEmail               = 'E-Mail';
$strTown                = 'Wohnort';
$strPostcode            = 'Postfach';
$strSubscribeInfo       = 'Zur Anmeldung bei einer oder mehreren unserer Newslettern ben&uuml;tzen Sie bitte das nachfolgende Formular!';
$strRequired            = 'rot';
$strRequired1           = 'Ben&ouml;tigte Felder';
$strSubscribeTitle      = 'Anmelden bei der Newsletter';
$strPleaseSelect        = 'Bitte w&auml;hlen Sie eine oder mehrere Newsletter, bei denen Sie sich anmelden wollen';
$strSubmit              = 'Anmelden bei den ausgew&auml;hlten Newslettern';
$strNotAvailable        = 'Derzeit sind keine Newsletter verf&uuml;gbar';
$strEnterName           = 'Bitte geben Sie Ihren Namen ein';
$strEnterEmail          = 'Bitte geben Sie Ihre E-Mail Adresse ein';
$strEnterList           = 'Bitte w&auml;hlen Sie ein Newsletter aus, bei der Sie sich anmelden wollen';
$strPleaseEnter    = 'Bitte geben Sie';
$strThanks              = 'Danke f&uuml;r Ihre Anmeldung bei unseren Newslettern.';
$strEmailConfirmation   = 'Sie erhalten in K&uuml;rze eine E-Mail mit der Best&auml;tigung der angemeldeten Newsletter.';
$strUnsubscribeTitle    = 'Abmelden von unseren Newslettern';
$strUnsubscribeDone     = 'Sie wurden von den ausgew&auml;hlten Newslettern abgemeldet, eine Best&auml;tigung erhalten Sie in K&uuml;rze per E-Mail.';
$strBack                = 'Zur&uuml;ck';
$strUnsubscribeInfo     = 'Abmelden von einer oder mehreren unserer Newslettern';
$strContinue            = 'Weiter';
$strUnsubscribeSelect   = 'Bitte w&auml;hlen Sie die Newsletter von denen Sie sich abmelden wollen';
$strAllLists            = 'Alle Listen';
$strNoLists             = 'Keine von diesen';
$strNoListsFound        = 'Sie wurden mit dieser E-Mail bei keiner unserer Newslettern angemeldet';
$strResubmit            = 'Erneut versuchen';
$strUnsubscribeSubmit   = 'Abmelden von den gew&auml;hlten Newslettern';
$strValuesMissing       = 'Die folgenden ben&ouml;tigten Felder fehlen';
$strConfirmInfo   = 'Danke f&uuml;r die Best&auml;tigung. Sie wurden f&uuml;r folgende Newsletter angemeldet:';
$strConfirmTitle   = 'Best&auml;tigungsseite';
$strUserNotFound  = 'User nicht gefunden';
$strConfirmFailInfo  = 'Es trat ein Fehler auf. Details:';
$strPreferHTMLEmail     = '&nbsp;&nbsp;E-Mails im HTML-Format (empfohlen!)';
$strPreferencesTitle    = 'Ihre Mitgliedschaftsdaten werden aktualisiert';
$strPreferencesInfo    = 'Bitte best&auml;tigen Sie die angezeigte Information und klicken Sie auf den "Aktualisieren"-Knopf';
$strUpdatePreferences  = 'Aktualisieren';
$strPreferencesEmailChanged = 'Ihre E-Mail Addresse wurde ge&auml;ndert. Bitte besuchen Sie den Link in der Email um die neue Email Addresse zu best&auml;tigen';
$strPreferencesNotificationSent = 'Sie erhalten in K&uuml;rze eine E-Mail mit der Best&auml;tigung der ver&auml;nderten Daten';
$strPreferencesUpdated = 'Vielen Dank. Ihre Information wurde aktualisiert.';
$strClickHere          = 'Hier anklicken';
$strThisLink           = 'dieses link';
$strToUnsubscribe      = 'Um Sich von diesem Newsletter abzumelden, besuchen Sie';
$strToUpdate           = 'Um Ihre Mitgliedschaftsdaten zu aktualisieren, besuchen Sie';
$strSendHTML           = 'Send HTML email';
$strYes                = 'Ja';
$strNo                 = 'Nein';
$strUnsubscribe        = 'Newsletter Abmelden';


?>