<?php

# language dependent text used in the interface for users (not admin)
# translated by WEBANICS.COMmunications
# translated for version 2.5.5

$strCharSet             = 'UTF-8';
$strName                = 'Nome';
$strAddress             = 'Indirizzo';
$strEmail               = 'Email';
$strTown                = 'Città';
$strPostcode            = 'CAP';
$strSubscribeInfo       = 'Iscriviti ad una o più Mailing List utilizzando il seguente Modulo';
$strRequired            = 'campi obbligatori';
$strSubscribeTitle      = 'Iscriviti alla Mailing List';
$strPleaseSelect        = 'Seleziona la Mailing List alla quale ti vuoi iscrivere';
$strSubmit              = 'Iscriviti alla Mailing List selezionata';
$strNotAvailable        = 'Mi dispiace, al momento non ci sono Mailing List disponibili';
$strEnterName           = 'Inserisci il tuo Nome';
$strEnterEmail          = 'Inserisci il tuo indirizzo Email';
$strInvalidHostInEmail  = 'Impossibile spedire Email! Controlla che l\'indirizzo Email sia scritto correttamente';
$strEnterList           = 'Seleziona la Mailing List alla quale ti vuoi iscrivere';
$strPleaseEnter         = 'Per favore, inserisci il tuo';
# ---the thanks message can contain placeholders
#$strThanks              = 'Caro/a [FIRST NAME], <br/>grazie per esserti iscritto alla Mailing List.';
$strThanks              = 'Grazie per esserti iscritto alla Mailing List.';
# ---the EmailConfirmation message can contain placeholders
#$strEmailConfirmation   = 'Il tuo indirizzo Email [email] è stato aggiunto al nostro sistema. Presto ti sarà spedita una Email di conferma di iscrizione alla Mailing List.';
$strEmailConfirmation   = 'Il tuo indirizzo Email è stato aggiunto al nostro sistema. Presto ti sarà spedita una Email di conferma di iscrizione alla Mailing List. Attenzione! Attiva la tua iscrizione, cliccando sul link nella Email di conferma.';
$strEmailFailed          = 'Si è verificato un errore durante l\'invio della Email, fai click su "Reload" per provare nuovamente.';
$strUnsubscribeTitle    = 'Cancella iscrizione alla Mailing List';
$strUnsubscribeDone     = 'Hai cancellato la tua iscrizione dalla Mailing List selezionata, presto ti sarà spedita una Email di conferma.';
$strBack                = 'Indietro';
$strUnsubscribeInfo     = 'Cancella la tua iscrizione da una o più Mailing List';
$strContinue            = 'Continua';
$strUnsubscribeSelect   = 'Seleziona la Mailing List dalla quale vuoi cancellare la tua iscrizione';
$strAllLists            = 'Tutte le Mailing List';
$strNoLists             = 'Nessuna delle Mailing List';
$strNoListsFound        = 'Non sei iscritto a nessuna Mailing List con questo indirizzo Email';
$strResubmit            = 'Reinserisci l\'indirizzo Email';
$strUnsubscribeSubmit   = 'Cancella iscrizione alla Mailing List';
$strValuesMissing       = 'Hai dimenticato di inserire i seguenti campi obbligatori';
$strConfirmInfo         = 'Grazie per aver confermato la tua iscrizione. La Mailing List alla quale ti sei iscritto è la seguente';
$strConfirmTitle        = 'Membro di PHPlist - Pagina di Conferma';
$strUserNotFound        = 'Utente non trovato';
$strUserAlreadyInitialised = 'Mi dispiace, la tua Password è già stata scelta';
$strConfirmFailInfo     = 'Mi dispiace, la tua conferma non è stata riconosciuta. Attenzione! Utilizza per intero l\'indirizzo web che hai ricevuto via Email.';
$strPreferHTMLEmail     = 'Preferisco ricevere Email in formato HTML';
$strPreferTextEmail     = 'Preferisco ricevere Email in formato TESTO';
$strPreferredFormat      = 'Formato Email preferito:';
$strText                 = 'TESTO';
$strHTML                = 'HTML';
$strPreferencesTitle    = 'Aggiorna le tue informazione';
$strPreferencesInfo     = 'Conferma che le seguenti informazioni sono corrette e fai click sul bottone "Aggiorna"';
$strUpdatePreferences   = 'Aggiorna';
$strPreferencesEmailChanged = 'Il tuo indirizzo Email è cambiato. Per confermare il tuo nuovo indirizzo Email, clicca sul Link che riceverai via Email';
$strPreferencesNotificationSent = 'Presto ti sarà spedita una Email di conferma dei cambiamenti fatti';
$strPreferencesUpdated = 'Grazie! Abbiamo aggiornato le tue informazioni.';
$strClickHere          = 'Clicca Qui';
$strThisLink           = 'questo link';
$strToUnsubscribe      = 'Per cancellare l\'iscrizione da questa Mailing List visita';
$strToUpdate           = 'Per aggiornare le tue informazioni visita';
$strSendHTML           = 'Spedisci Email in formato HTML';
$strYes                = 'Si';
$strNo                 = 'No';
$strUnsubscribe        = 'Cancella Iscrizione';
$strAttachmentIntro     = 'Questo messaggio contiene allegati che possono essere visualizzati con un web browser:';
$strLocation           = 'Indirizzo Web';
$strFrequency           = 'Con che frequenza ti spediamo messaggi';
$strHourly             = 'ogni ora';
$strDaily               = 'quotidianamente';
$strWeekly             = 'settimanalmente';
$strMonthly             = 'mensilmente';
$strChoosePassword      = 'Scegli Password';
$strConfirmPassword    = 'Conferma Password';
$strEnterPassword       = 'Inserisci la tua Password';
$strForgotPassword     = 'Password Dimenticata';
$strPassword           = 'Password';
$strPassword2           = 'Conferma Password';
$strPasswordsNoMatch    = 'Le Passwords non sono uguali';
$strInvalidPassword     = 'Errore: Indirizzo Email o Password invalide';
$strPasswordSent        = 'La tua Password ti è stata spedita via Email. Dovresti riceverla tra pochi minuti';
$strPasswordRemindSubject = 'La tua Password per la Mailing List';
$strPasswordRemindMessage = 'La tua Password è ';
$strPasswordRemindInfo = 'Per ricevere la tua Password via Email, reinserisci la tua Email e clicca sul bottone "'.$strForgotPassword.'".';
$strLogin               = 'Login';
$strLoginTitle          = 'Inserisci il tuo indirizzo Email e la tua Password';
$strLoginInfo           = 'Questa pagina richiede una Password. Inserisci il tuo indirizzo Email e la tua Password';
$strPersonalLocationInfo = '
  <p>Questa pagina richiede una identificazione personale che può essere trovata in ogni Email che ti abbiamo spedito.<br/>
  Attenzione! Se hai cliccato sull\'indirizzo web e si verifica questo errore, copia ed incolla per intero l\'indirizzo web che hai ricevuto via Email nella barra degli indirizzi del tuo web browser.</p>
  <p>Se non conosci l\'indirizzo web, puoi fare una richiesta per riceverne uno via Email. Inserisci il tuo indirizzo Email e clicca su "Continua"';
$strPersonalLocationSent = '<h1>Operazione conclusa con successo! Presto ti sarà spedita una Email con il tuo indirizzo web personale</h1>';

?>
