
<?php
# language dependent text used in the interface for users (not admin)
# Italian Module translated by Bartolotta Gioachino developers@rockitalia.com http://www.ladysilvia.net
# translated for version 1.1.3b

$strName                = 'Nome';
$strAddress             = 'Indirizzo';
$strEmail               = 'Email';
$strTown                = 'Città';
$strPostcode            = 'Ca.p';
$strSubscribeInfo       = 'Sottoscrivi una o più fra le nostre mailing lists utilizzando il form sottostante';
$strRequired            = 'campi richiesti';
$strSubscribeTitle      = 'Sottoscrivi le nostre mailing lists';
$strPleaseSelect        = 'Scegli le liste che vuoi sottoscrivere';
$strSubmit              = 'Sottoscrivi le Mailinglists selezionate';
$strNotAvailable        = 'Spiacente, attualmente non ci sono liste disponibili';
$strEnterName           = 'Inserisci il tuo nome per favore';
$strEnterEmail          = 'Inserisci il tuo indirizzo email per favore';
$strEnterList           = 'Scegli una lista da sottoscrivere per favore';
$strThanks              = 'Grazie per aver sottoscritto le nostre liste';
$strEmailConfirmation   = 'Presto riceverai una email con la conferma delle liste che hai sottoscritto.';
$strUnsubscribeTitle    = 'Cancellati dalle nostre Mailinglists';
$strUnsubscribeDone     = 'Sei stato cancellato dalle nostre mailing lists che hai selezionato e a breve riceverai una email di conferma.';
$strBack                = 'Indietro';
$strUnsubscribeInfo     = 'Cancellati da una o più mailing lists';
$strContinue            = 'Continua';
$strUnsubscribeSelect   = 'Scegli le liste dalle quali ti vuoi cancellare';
$strAllLists            = 'Tutte le Liste';
$strNoLists             = 'Nessuna di loro';
$strNoListsFound        = 'Spiacenti, ma non sei inscritto a nessuna delle nostre mailing lists con queste email.';
$strResubmit            = 'Re-Submit Email';
$strUnsubscribeSubmit   = 'Cancellati dalle Mailing lists selezionate';
$strValuesMissing       = 'Mancano i seguenti valori richiesti';

?>

