<?php

# language dependent text used in the interface for users (not admin)

$strCharSet             = 'UTF-8';
$strLancode             = 'pt'; ## two letter iso code
$strLandir              = 'ltr'; ## language direction (ltr or rtl)
$strName                = 'Nome';
$strEmail               = 'Endereço de email';
$strAddress             = 'Morada';
$strTown                = 'Localidade';
$strPostcode            = 'Código postal';
$strSubscribeInfo       = 'Use o formulário abaixo para subscrever uma ou mais das nossas listas de distribuição';
$strRequired            = 'campo obrigatório';
$strSubscribeTitle      = 'Subscreva as nossas listas de distribuição';
$strPleaseSelect        = 'Por favor seleccione a(s) lista(s) que pretende subscrever';
$strSubmit              = 'Subscreva as listas seleccionadas';
$strNotAvailable        = 'Lamentamos, mas ainda não existem listas disponíveis.';
$strEnterName           = 'Por favor insira o seu nome';
$strEnterEmail          = 'Por favor introduza o seu endereço de email';
$strConfirmEmail        = 'Confirme o seu endereço de email';
$strInvalidHostInEmail  = 'Lamentamos mas não conseguimos entregar email no domínio indicado. Por favor certifique-se que introduziu correctamente o seu endereço de email';
$strEnterList           = 'Por favor seleccione a lista que pretende subscrever';
$strPleaseEnter         = 'Por favor introduza';
# the thanks message can contain placeholders
#$strThanks              = 'Obrigado por subscrever a(s) nossa(s) listas de distribuição';
$strThanks              = 'Estimado(a) [FIRST NAME], <br/>Obrigado por subscrever a(s) nossa(s) listas de distribuição';
# the EmailConfirmation message can contain placeholders
#$strEmailConfirmation   = 'O seu endereço de email foi acrescentado ao nosso sistema. Em breve receberá uma mensagem com a confirmação da(s) lista(s) que subscreveu. Por favor certifique-se que clica no endereço enviado nessa mensagem para confirmar a sua subscrição.';
$strEmailConfirmation   = 'O seu endereço de email [email] foi acrescentado ao nosso sistema. Em breve receberá uma mensagem com a confirmação da(s) lista(s) que subscreveu. Por favor certifique-se que clica no endereço enviado nessa mensagem para confirmar a sua subscrição.';
$strEmailFailed      = 'Lamentamos mas não conseguimos enviar-lhe o email solicitando a sua confirmação. Por favor clique no botão "<em>Reload</em>" ou "Refrescar" para tentar novamente.';
$strUnsubscribeTitle    = 'Cancelar a sua subscrição da(s) nossa(s) lista(s) de distribuição';
$strUnsubscribeDone     = 'Procedemos ao cancelamento da sua subscrição da(s) lista(s) de distribuição seleccionada(s) e brevemente receberá uma confirmação por email.';
$strUnsubscribedNoConfirm = 'Procedemos ao cancelamento da sua subscrição da(s) lista(s) de distribuição seleccionada(s)';
$strBack                = 'Voltar atrás';
$strUnsubscribeInfo     = 'Cancelar a subscrição de uma ou várias das nossas listas de distribuição';
$strContinue            = 'Continuar';
$strUnsubscribeSelect   = 'Por favor seleccione a(s) lista(s) cuja subscrição pretende cancelar.';
$strAllLists            = 'Todas as listas';
$strNoLists             = 'Nenhuma das listas';
$strUnsubscribeRequestForReason = 'É com tristeza que o vemos partir e que vemos que já não demonstra interesse nas nossas listas. Para nos ajudar a melhorar os nossos servi%ccedil;os ficariamos agradecidos se nos pudesse dizer a razão:';
$strUnsubscribeFinalInfo = '<br/><b>Por favor note</b>: nesta página poderá cancelar a subscrição da(s) nossa(s) lista(s) de distribuição <b>permanentemente</b>. Se pretender alterar o seu email, ou alterar que lista(s) de subscrição deverá receber, por favor siga até <a href="[PREFERENCESURL]">alterar as suas preferências</a>';
$strNoListsFound        = 'Lamentamos, mas este endereço de email não se encontra nas bases de dados de assinantes de nenhuma das nossas listas.';
$strResubmit            = 'Reenviar email';
$strUnsubscribeSubmit   = 'Cancelar a subscrição da(s) lista(s) seleccionada(s).';
$strValuesMissing       = 'Não preencheu os seguintes dados obrigatórios';
$strConfirmInfo         = 'Obrigado pela confirmação da sua subscrição. A(s) lista(s) que subscreve encontra(m)-se listada(s) abaixo.';
$strConfirmTitle        = 'Página de confirmação da subscrição';
$strUserNotFound        = 'Assinante não encontrado';
$strUserAlreadyInitialised = 'Lamentamos, mas a sua senha já foi definida';
$strConfirmFailInfo     = 'Lamentamos, mas o seu pedido de confirmação não foi reconhecido. Certifique-se que usa a totalidade do endereço conforme este surge na mensagem de email que lhe foi enviada. Por vezes, esse endereço é quebrado em duas linhas.';
$strPreferHTMLEmail     = 'Eu prefiro receber mensagens no formato HTML';
$strPreferTextEmail     = 'Eu prefiro receber mensagens no formato Texto';
$strPreferredFormat    = 'Formato preferido:';
$strText         = 'Texto';
$strHTML        = 'HTML';
$strPreferencesTitle    = 'Actualize os seus dados';
$strPreferencesInfo     = 'Por favor confirme se a informação abaixo está correcta e clique no botão "Actualizar".';
$strUpdatePreferences   = 'Actualizar';
$strPreferencesEmailChanged = 'O seu endereço de email foi alterado. Por favor visite o endereço indicado na mensagem que vai receber por email, para confirmar o seu novo endereço.';
$strYouAreBlacklisted = 'O seu email está registado na nossa "Lista Negra", o que significa que vecê nos pediu para que nunca mais lhe enviassemos emails.<br/>Para que possa receber emails novamente é necessária intervenço do administrador. Contact-nos dizendoo explicitamente que deseja tornar a receber os nossos boletins e será removido da "Lista Negra".';
$strPreferencesNotificationSent = 'Receberá uma mensagem por email contendo as alterações efectuadas.';
$strPreferencesUpdated = 'Obrigado pela actualização. Os seus dados foram actualizados.';
$strClickHere          = 'Clique aqui';
$strThisLink           = 'esta ligação';
$strToUnsubscribe      = 'Para cancelar a subscrição desta lista visite';
$strToUpdate           = 'Para actualizar os seus dados visite';
$strSendHTML           = 'Enviar email em HTML';
$strYes                = 'Sim';
$strNo                 = 'Não';
$strUnsubscribe        = 'Cancelar subscrições';
$strAllMailinglists    = 'Todas as listas';
$strAttachmentIntro     = 'Esta mensagem contém anexos que podem ser vistos com um <em>web browser</em>:';
$strLocation       = 'Endereço/URL';
$strFrequency       = 'Com que frequência lhe enviaremos mensagens';
$strHourly         = 'Hora a hora';
$strDaily         = 'Diariamente';
$strWeekly         = 'Semanalmente';
$strMonthly         = 'Mensalmente';
$strChoosePassword      = 'Por favor escolha uma senha';
$strConfirmPassword    = 'Confirme a sua senha';
$strEnterPassword     = 'Por favor introduza a sua senha';
$strForgotPassword     = 'Esqueci-me da senha';
$strForgotPasswordEmailBody = '
    Caro administrador das listas de subscrição

    Eu esqueci-me da minha senha do sistema de listas de sibscrição phplist.
    Poderá repô-la e informar-me qual é?

    Obrigado
';    

$strPassword       = 'Senha';
$strPassword2       = 'Confirmar senha';
$strPasswordsNoMatch   = 'As senhas não condizem';
$strEmailsNoMatch     = 'Os endereços de email não são iguais';
$strInvalidPassword     = 'Erro: endereço de email ou senha inválidos';
$strPasswordSent      = 'A sua senha foi enviada para o seu endereço de email. Deverá recebê-la dentro de momentos';
$strPasswordRemindSubject = 'A sua senha para as nossas listas';
$strPasswordRemindMessage = 'A sua senha é ';
$strPasswordRemindInfo = 'Para receber a sua senha por email, por favor introduza o seu endereço de email e clique no botão "'.$strForgotPassword.'"';
$strLogin         = 'Iniciar sessão';
$strLoginTitle        = 'Por favor introduza o seu endereço de email e senha';
$strLoginInfo       = 'Esta página requer uma senha. Por favor introduza o seu endereço de email e a sua senha';
$strPersonalLocationInfo = '
  <p>Para aceder a esta página é necessária uma identificação pessoal que pode ser encontrada em cada mensagem que lhe enviamos.<br/>
  Se clicou neste endereço <em>web</em> e se obteve este erro, por favor certifique-se que coloca a totalidade do endereço no seu <em>browser</em>. Por vezes, os programas de email quebram este endereço em mais de uma linha.</p>
  <p>Se não conhece esse endereço <em>web</em>, pode solicitar o envio de uma mensagem que lho dará a conhecer.
  Por favor introduza o seu endereço de email no campo e clique "Continuar"
';
$strPersonalLocationSent = '<h1>Sucesso! Deverá receber a mensagem com o seu endereço/URL pessoal dentro de momentos</h1>';
$strUserExists   = '<br/>Já existe um utilizador com este email e os nossos registos contêm uma senha diferente';
$strUserExistsExplanationStart = '<br/>Para obter a sua senha, clique ';
$strUserExistsExplanationLink = 'aqui';
$strUserExistsExplanationEnd = ' para ir até à página onde poderá requerer a sua localização pessoal';
$strExplainBlacklist = 'O endereço de email que introduziu será guardado na nossa base de dados apenas com o propósito de bloquear quaisquer emails enviados por este sistema.';

$strUserExistsResubscribe = 'Já existe um assinante com este endereço';
$strUserExistsResubscribeExplanation = 'Visite a <a href="%s">página de preferências</a> para actualizar a sua informação.';


$strForwardTitle = 'Reencaminhe a mensagem para alguém';
$strForwardSubtitle = 'Reencaminhar a mensagem com assunto ';
$strForwardEnterEmail = 'Por favor introduza um endereço de email válido para reencaminhar';
$strForwardInvalidEmail = '%s não é um endereço de email válido';
$strForwardBlacklistedEmail = 'O destinatário pediu para não receber emails deste sistema.';
$strForwardEnterEmails = 'Por favor introduza nesta caixa no máximo %s endereços de email válidos para reencaminhar, um por cada linha';
$strForwardPersonalNote = 'Pode introduzir uma mensagem de texto simples (no máximo %d caracteres) que será incluída no início da mensagem reencaminhada';
$strForwardSuccessInfo ='Esta mensagem foi reencaminhada';
$strForwardFailInfo = 'Falhou ao reencaminhar a mensagem';
$strForwardAlreadyDone = 'Esta mensagem já foi reencaminhada com sucesso anteriormente para este endereço de email';
$strForwardCountReached = 'Alcançou o número máximo de reencaminhamentos';
$strForwardNoteLimitReached = 'Alcançou o tamanho máximo para a nota pessoal';
$strForwardFooter = 'Esta mensagem foi reencaminhada por [FORWARDEDBY].
  Não ficou automaticamente inscrito nesta lista de divulgação.
  Para assinar esta lista de divulgação visite';
$strForward = 'Reencaminhar';
$strFwd = 'Re'; # short version of forward for email subject


?>
