<?php
# language dependent text used in the interface for users (not admin)
$strCharSet = 'UTF-8';
$strName = 'Nome';
$strAddress = 'Endereço';
$strEmail = 'E-mail';
$strTown = 'Cidade';
$strPostcode = 'C&oacute;digo Postal';
$strSubscribeInfo = 'Use o formul&aacute;rio abaixo para se inscrever em uma ou mais listas de distribui&ccedil;&atilde;o';
$strRequired = 'campo obrigat&oacute;rio';
$strSubscribeTitle = 'Inscreva-se nas nossas listas de distribui&ccedil;&atilde;o';
$strPleaseSelect = 'Por favor selecione a(s) lista(s) nas quais pretende se inscrever';
$strSubmit = 'Inscrever nas listas selecionadas';
$strNotAvailable = 'Lamentamos, mas ainda n&atilde;o existem listas dispon&iacute;veis.';
$strEnterName = 'Por favor informe o seu nome';
$strEnterEmail = 'Por favor informe o seu endere&ccedil;o de e-mail';
$strInvalidHostInEmail = 'Lamentamos mas n&atilde;o conseguimos entregar e-mails no dom&iacute;nio indicado. Por favor certifique-se que informou corretamente o seu endere&ccedil;o de e-mail';
$strEnterList = 'Por favor selecione a lista na qual pretende se inscrever';
$strPleaseEnter = 'Por favor informe';
# the thanks message can contain placeholders
# $strThanks = 'Obrigado por subscrever a(s) nossa(s) listas de distribui&ccedil;&atilde;o';
$strThanks = 'Caro(a) [FIRST NAME], <br/>Obrigado por se inscrever na(s) nossa(s) listas de distribui&ccedil;&atilde;o';
# the EmailConfirmation message can contain placeholders
# $strEmailConfirmation = 'O seu endere&ccedil;o de e-mail foi acrescentado ao nosso sistema. Em breve receber&aacute; uma mensagem com a confirma&ccedil;&atilde;o da(s) lista(s) que subscreveu. Por favor certifique-se que clica no endere&ccedil;o enviado nessa mensagem para confirmar a sua inscri&ccedil;&atilde;o.';
$strEmailConfirmation = 'O seu endere&ccedil;o de e-mail [email] foi registrado no nosso sistema. Em breve receber&aacute; uma mensagem com a confirma&ccedil;&atilde;o da(s) lista(s) em que se inscreveu. Por favor certifique-se de clicar no endere&ccedil;o enviado nessa mensagem para confirmar a sua inscri&ccedil;&atilde;o.';
$strEmailFailed = 'Lamentamos mas n&atilde;o conseguimos lhe enviar o e-mail solicitando a sua confirma&ccedil;&atilde;o. Por favor clique no bot&atilde;o "<em>Atualizar</em>" ou "Reload" para tentar novamente.';
$strUnsubscribeTitle = 'Cancelar a sua inscri&ccedil;&atilde;o da(s) nossa(s) lista(s) de distribui&ccedil;&atilde;o';
$strUnsubscribeDone = 'Procedemos com o cancelamento da sua inscri&ccedil;&atilde;o da(s) lista(s) de distribui&ccedil;&atilde;o selecionada(s) e em breve receber&aacute; uma confirma&ccedil;&atilde;o por e-mail.';
$strBack = 'Voltar';
$strUnsubscribeInfo = 'Cancelar a inscri&ccedil;&atilde;o de uma ou v&aacute;rias das nossas listas de distribui&ccedil;&atilde;o';
$strContinue = 'Continuar';
$strUnsubscribeSelect = 'Por favor selecione a(s) lista(s) cuja inscri&ccedil;&atilde;o pretende cancelar.';
$strAllLists = 'Todas as listas';
$strNoLists = 'Nenhuma das listas';
$strUnsubscribeRequestForReason = '&Eacute; com tristeza que o vemos partir. Para nos ajudar a melhorar os nossos servi&ccedil;os ficariamos agradecidos se pudesse nos dizer a raz&atilde;o:';
$strUnsubscribeFinalInfo = '<br/><b>Importante</b>: nesta página você vai <b>remover seu e-mail para sempre</b> e nunca mais receberá quaisquer mensagens enviadas por nós. Se você quer apenas alterar seu e-mail ou cancelar sua inscrição de alguma lista específica, por favor <a href="[PREFERENCESURL]">atualize suas preferências</a>';
$strNoListsFound = 'Lamentamos, mas este endere&ccedil;o de e-mail n&atilde;o se encontra nas bases de dados de assinantes de nenhuma das nossas listas.';
$strResubmit = 'Reenviar e-mail';
$strUnsubscribeSubmit = 'Cancelar a inscri&ccedil;&atilde;o da(s) lista(s) selecionada(s).';
$strValuesMissing = 'N&atilde;o preencheu os seguintes dados obrigat&oacute;rios';
$strConfirmInfo = 'Obrigado pela confirma&ccedil;&atilde;o da sua inscri&ccedil;&atilde;o. A(s) lista(s) nas quais se inscreveu estão listada(s) abaixo.';
$strConfirmTitle = 'P&aacute;gina de confirma&ccedil;&atilde;o da inscri&ccedil;&atilde;o';
$strUserNotFound = 'Assinante n&atilde;o encontrado';
$strUserAlreadyInitialised = 'Lamentamos, mas a sua senha j&aacute; foi definida';
$strConfirmFailInfo = 'Lamentamos, mas o seu pedido de confirma&ccedil;&atilde;o n&atilde;o foi reconhecido. Certifique-se que copiou todo o endere&ccedil;o conforme consta na mensagem de e-mail que lhe foi enviada. As vezes, esse endere&ccedil;o &eacute; quebrado em duas linhas.';
$strPreferHTMLEmail = 'Eu prefiro receber mensagens no formato HTML';
$strPreferTextEmail = 'Eu prefiro receber mensagens no formato Texto';
$strPreferredFormat = 'Formato preferido:';
$strText = 'Texto';
$strHTML = 'HTML';
$strPreferencesTitle = 'Atualize os seus dados';
$strPreferencesInfo = 'Por favor confirme se a informa&ccedil;&atilde;o abaixo est&aacute; correta e clique no bot&atilde;o "Atualizar".';
$strUpdatePreferences = 'Atualizar';
$strPreferencesEmailChanged = 'O seu endere&ccedil;o de e-mail foi alterado. Por favor visite o endere&ccedil;o indicado na mensagem que vai receber por e-mail, para confirmar o seu novo endere&ccedil;o.';
$strYouAreBlacklisted = 'O seu email est&aacute; registado na nossa "Lista Negra", o que significa que vec&ecirc; nos pediu para que nunca mais lhe enviassemos emails.<br/>Para que possa receber emails novamente &eacute; necess&aacute;ria interven&ccedil;o do administrador. Contate-nos dizendo explicitamente que deseja voltar a receber os nossos boletins e será removido da "Lista Negra".';
$strPreferencesNotificationSent = 'Receber&aacute; uma mensagem por e-mail contendo as altera&ccedil;&otilde;es realizadas.';
$strPreferencesUpdated = 'Obrigado. Os seus dados foram atualizados.';
$strClickHere = 'Clique aqui';
$strThisLink = 'este link';
$strToUnsubscribe = 'Para cancelar a inscri&ccedil;&atilde;o desta lista visite';
$strToUpdate = 'Para atualizar os seus dados visite';
$strSendHTML = 'Enviar e-mail em HTML';
$strYes = 'Sim';
$strNo = 'N&atilde;o';
$strUnsubscribe = 'Cancelar inscri&ccedil;&otilde;es';
$strAllMailinglists = 'Todas as listas';
$strAttachmentIntro = 'Esta mensagem cont&eacute;m anexos que podem ser vistos com um <em>web browser</em>:';
$strLocation = 'Endere&ccedil;o/URL';
$strFrequency = 'Com que frequ&ecirc;ncia lhe enviaremos mensagens';
$strHourly = 'Hora a hora';
$strDaily = 'Diariamente';
$strWeekly = 'Semanalmente';
$strMonthly = 'Mensalmente';
$strChoosePassword = 'Por favor escolha uma senha';
$strConfirmPassword = 'Confirme a sua senha';
$strEnterPassword = 'Por favor informe a sua senha';
$strForgotPassword = 'Esqueci a minha senha';
$strPassword = 'senha';
$strPassword2 = 'Confirmar senha';
$strPasswordsNoMatch = 'As senhas n&atilde;o conferem';
$strEmailsNoMatch = 'Os endere&ccedil;os de email n&atilde;o s&atilde;o iguais';
$strInvalidPassword = 'Erro: endere&ccedil;o de e-mail ou senha inv&aacute;lidos';
$strPasswordSent = 'A sua senha foi enviada para o seu endere&ccedil;o de e-mail. Dever&aacute; receb&ecirc;-la em breve';
$strPasswordRemindSubject = 'A sua senha para as nossas listas';
$strPasswordRemindMessage = 'A sua senha é ';
$strPasswordRemindInfo = 'Para receber a sua senha por e-mail, por favor informe o seu endere&ccedil;o de e-mail e clique no bot&atilde;o "'.$strForgotPassword.'"';
$strLogin = 'Login';
$strLoginTitle = 'Por favor informe o seu endere&ccedil;o de e-mail e senha';
$strLoginInfo = 'Esta p&aacute;gina requer uma senha. Por favor informe o seu endere&ccedil;o de e-mail e a senha';
$strPersonalLocationInfo = '
<p>Para acessar esta p&aacute;gina &eacute; necess&aacute;ria uma identifica&ccedil;&atilde;o pessoal que pode ser encontrada nas mensagens que lhe enviamos.<br/>
Se você acessou este endere&ccedil;o <em>web</em> através de uma mensagem de e-mail e obteve este erro, por favor certifique-se de que o endereço copiado do e-mail esta completo. As vezes, os programas de e-mail quebram este endere&ccedil;o em mais de uma linha.</p>
<p>Se n&atilde;o sabe ou não tem esse endere&ccedil;o <em>web</em>, pode solicitar o envio de uma mensagem com o mesmo.
Por favor informe o seu endere&ccedil;o de e-mail no campo abaixo e clique "Continuar"
';
$strPersonalLocationSent = '<h1>Sucesso! Dever&aacute; receber a mensagem com o seu endere&ccedil;o/URL pessoal em breve</h1>';
$strUserExists = '<br/>Um utilizador com esse email j&aacute; existe e os nossos registos cont&ecirc;m uma senha diferente';
$strUserExistsExplanationStart = '<br/>Para obter sua senha, clique ';
$strUserExistsExplanationLink = 'aqui';
$strUserExistsExplanationEnd = ' para ir para a página onde você pode solicitar o endereço de sua página pessoal';
$strForwardTitle = 'Encaminhar a mensagem para alguém';
$strForwardSubtitle = 'Encaminhando a mensagem com assunto ';
$strForwardEnterEmail = 'Por favor informe um e-mail válido para encaminhar';
$strForwardSuccessInfo ='A mensagem foi encaminhada';
$strForwardFailInfo = 'O encaminhamento da mensagem falhou';
$strForwardAlreadyDone = 'Esta mensagem já foi encaminhada com sucesso para o e-mail informado';
$strForwardFooter = 'Essa mensagem foi encaminhada a você por [FORWARDEDBY].
Você não foi inscrito nessa lista de e-mails automaticamente.
Para se inscrever nessa lista acesse';
$strForward = 'Encaminhar';
$strFwd = 'Enc'; # short version of forward for email subject
$strConfirmEmail = 'Confirme o seu endereço de e-mail';
