<?php

# language dependent text used in the interface for users (not admin)

$strCharSet             = 'UTF-8';
$strLancode             = 'sr'; ## two letter iso code
$strLandir              = 'ltr'; ## language direction (ltr or rtl)
$strName                = 'Ime';
$strAddress             = 'Adresa';
$strEmail               = 'Email adresa';
$strTown                = 'Grad';
$strPostcode            = 'Poštanska adresa';
$strSubscribeInfo       = '<h3>Pretplatite se na naš Bilten</h3>';
$strRequired            = 'potrebna polja su označena crvenom bojom';
$strSubscribeTitle      = 'Pretplatite se na naš Bilten';
$strPleaseSelect        = 'odaberite bilten na koji želite da se pretplatite';
$strSubmit              = 'Pretplatite se na odabrani bilten';
$strNotAvailable        = 'Izvinite, trenutno nema dostupnih biltena';
$strEnterName           = 'Unesite vaše ime';
$strEnterEmail          = 'Unesite važeću email adresu';
$strConfirmEmail        = 'Potvrdite vašu email adresu';
$strInvalidHostInEmail  = 'Izvinite, taj email domen je nedostupan, molimo proverite da li ste pravilno uneli email adresu';
$strEnterList           = 'Odaberite bilten na koji želite da se pretplatite';
$strPleaseEnter         = 'Unesite';
# the thanks message can contain placeholders
#$strThanks              = 'Dear [FIRST NAME], <br/>Thank you for subscribing to our lists.';
$strThanks              = 'Hvala Vam na prijavi na naš bilten.';
# the EmailConfirmation message can contain placeholders
#$strEmailConfirmation   = 'Your email [email] has been added to our system. You will be e-mailed shortly with confirmation of the lists you have subscribed to.';
$strEmailConfirmation   = 'Vaša email adresa [email] je dodata u sistem. Primićete poruku sa zahtevom da potvrdite vašu pretplatu. Molimo vas da kliknete na link u toj poruci kako bi potvrdili vašu pretplatu.';
$strEmailFailed          = 'Izvinite, slanje poruke za potvrdu nije uspelo, molimo kliknite "Učitaj ponovo" da pokušate ponovo. Ako i dalje ne radi, kontaktirajte administratora.';
$strUnsubscribeTitle    = 'Odjavite se sa našeg biltena';
$strUnsubscribeDone     = 'Odjavljeni ste sa našeg biltena i uskoro ćete primiti poruku potvrde.';
$strUnsubscribedNoConfirm = 'Odjavljeni ste sa ovog bilten sistema';
$strBack                = 'Nazad';
$strUnsubscribeInfo     = 'Odjavite se sa našeg biltena';
$strContinue            = 'Nastavi';
$strUnsubscribeSelect   = 'Molimo odaberite bilten sa kojeg želite da se odjavite';
$strAllLists            = 'Sve liste';
$strNoLists             = 'Nijedna';
$strUnsubscribeRequestForReason = 'Žao nam je što više niste zainteresovani za naš bilten. Kako bi nam pomogli da unapredimo naše usluge, bili bismo Vam zahvalni ako bi nam rekli zašto:';
$strUnsubscribeFinalInfo = '<br/><b>Molimo obratite pažnju</b>: ova strana služi za odjavu sa našeg bilten sistema <b>zauvek</b>. Ako želite da promenite vašu email adresu, ili ako želite da promenite koje biltene primate, molimo da <a href="[PREFERENCESURL]">ažurirate vaša podešavanja</a> umesto toga';
$strNoListsFound        = 'Izvinite, niste pretplaćeni ni na jedan od naših biltena sa ovom email adresom.';
$strResubmit            = 'Podnesi ponovo';
$strUnsubscribeSubmit   = 'Odjavite se sa označenih biltena';
$strValuesMissing       = 'Nedostaju sledeće potrebne vrednosti';
$strConfirmInfo         = 'Hvala Vam na potvrdi pretplate na naše biltene. Bilteni na koje ste pretplaćeni su izlistani ispod';
$strAlreadyConfirmed    = 'Već smo primili vašu potvrdu ranije.';
$strConfirmTitle        = 'phpList strana za potvrdu';
$strUserNotFound        = 'Pretplatnik nije pronađen';
$strUserAlreadyInitialised = 'Izvinite, vaša lozinka je već podešena';
$strConfirmFailInfo     = 'Izvinite, vaš zahtev za potvrdu nije prepoznat. Molimo proverite da li koristite punu veb adresu kao što je pomenutu u email-u koji ste primili. Ponekad ova veb adresa može biti u više redova.';
$strPreferHTMLEmail     = 'Želeo bih da primam email u HTML formatu';
$strPreferTextEmail     = 'Želeo bih da primam email u Tekst formatu';
$strPreferredFormat      = 'Željeni format za email poruke:';
$strText                 = 'Tekst';
$strHTML                = 'HTML';
$strPreferencesTitle    = 'Ažurirajte vaše postavke';
$strPreferencesInfo     = 'Molimo proverite da je informacija ispod tačna i kliknite dugme "Ažuriraj"';
$strUpdatePreferences   = 'Ažuriraj';
$strPreferencesEmailChanged = 'Vaša email adresa je promenjena. Molimo posetite link u poruci koju ćete primiti kako bi potvrdili vašu novu email adresu';
$strYouAreBlacklisted = 'Vaša email adresa se nalazi na našoj "Ne šalji" listi, što znači da ste tražili od nas da vam ne šaljemo biltene. <br/>
Kako bi vam ponovo slali biltene, potrebna je ručna intervencija od strane našeg administratora. Molimo kontaktirajte nas sa zahtevom da želite ponovo da primate naše biltene.';
$strPreferencesNotificationSent = 'Primićete obaveštenje o promenama';
$strPreferencesUpdated = 'Hvala vam. Ažurirali smo vaše podatke.';
$strClickHere          = 'Kliknite ovde';
$strThisLink           = 'ovaj link';
$strToUnsubscribe      = 'Ako više ne želite da primate biltene, ';
$strToUpdate           = 'Da ažurirate vaše postavke i da se odjavite posetite';
$strSendHTML           = 'Pošalji HTML email';
$strYes                = 'Da';
$strNo                 = 'Ne';
$strUnsubscribe        = 'Odjavi se';
$strAllMailinglists    = 'Svi bilteni';
$strAttachmentIntro     = 'Ova poruka sadrži priloge koji se mogu pregledati sa veb čitačem:';
$strLocation           = 'Lokacija';
$strFrequency           = 'Koliko često vam šaljemo poruke';
$strHourly             = 'Po satu';
$strDaily               = 'Dnevno';
$strWeekly             = 'Dnevno';
$strMonthly             = 'Mesečno';
$strChoosePassword      = 'Molimo izaberite lozinku';
$strConfirmPassword    = 'Potvrdite vašu lozinku';
$strEnterPassword       = 'Molimo unesite vašu lozinku';
$strForgotPassword     = 'Zaboravljena lozinka';
$strForgotPasswordEmailBody = '
    Poštovani
    Zaboravio/Zaboravila sam svoju lozinku za phpList sistem.
    Možete li je resetovati na nešto drugo i obavestiti me koja je?
    Hvala
';    

$strPassword           = 'Lozinka';
$strPassword2           = 'Potvrdi lozinku';
$strPasswordsNoMatch    = 'Lozinke nisu iste';
$strEmailsNoMatch     = 'Unesene email adrese se ne poklapaju';
$strEmailNotValid  = 'Email adresa nije važeća';
$strInvalidPassword     = 'Greška: nevažeća email adresa ili lozinka';
$strPasswordSent        = 'Vaša lozinka je poslata. Primićete je za nekoliko minuta';
$strPasswordRemindSubject = 'Vaša lozinka za naš bilten';
$strPasswordRemindMessage = 'Vaša lozinka je ';
$strPasswordRemindInfo = 'Da primite lozinku na email, molimo unesite vašu email adresi i kliknite "'.$strForgotPassword.'" dugme.';
$strLogin               = 'Prijava';
$strLoginTitle          = 'Molimo unesite vašu email adresu i lozinku';
$strLoginInfo           = 'Ova strana zahteva lozinku. Molimo unesite vašu email adresu i lozinku';
$strPersonalLocationInfo = '
  <p>Ova strana zahteva ličnu identifikaciju koja se može naći u svakoj poruci koju primite od nas.</p>
  <p>Ako ste kliknuli ovu lokaciju, a dobijate ovu grešku, molimo prekopirajte celu liniju u polje lokacije u vašem veb čitaču. Ponekad se lokacija prelama u više redova.</p>
  <p>Ako ne znate lokaciju, unesite vašu email adresu u polje i kliknite "Nastavi"</p>
';
$strPersonalLocationSent = '<h3>Uspeh! Uskoro ćete primiti poruku sa vašom ličnom lokacijom</h3>';
$strUserExists   = 'Pretplatnik sa tom adresom već postoji, a naši zapisi sadrže drugu lozinku';
$strUserExistsExplanationStart = 'Kako bi dobili vašu lozinku, kliknite ';
$strUserExistsExplanationLink = 'ovde';
$strUserExistsExplanationEnd = ' da bi otišli na stranu gde možete tražiti vašu ličnu lokaciju';
$strExplainBlacklist = 'Email adresa koju ste uneli će biti zapisana u našoj bazi podataka jedino u svrhu blokiranja bilo kojih email poruka poslatih iz ovog sistema.';

$strUserExistsResubscribe = 'Pretplatnik sa tom adresom već postoji';
$strUserExistsResubscribeExplanation = 'Posetite <a href="%s">stranu sa podešavanjima</a> da ažurirate vaše informacije.';


$strForwardTitle = 'Prosledi nekome poruku';
$strForwardSubtitle = 'Prosleđujem poruku sa naslovom ';
$strForwardEnterEmail = 'Molimo unesite važeću email adresu za prosleđivanje';
$strForwardInvalidEmail = '%s nije važeća email adresa';
$strForwardBlacklistedEmail = 'Primalac je tražio da ne prima email poruke od ovog sistema.';
$strForwardEnterEmails = 'Molimo unesite maksimum od %s važećih email adresa za prosleđivanje u ovom polju, jednu po liniji';
$strForwardPersonalNote = 'Možete uneti običnu tekstualnu poruku (od maksimum %d karaktera) koja će biti dodata na početak prosleđenog email-a';
$strForwardSuccessInfo ='Poruka je prosleđena';
$strForwardFailInfo = 'Neuspešno prosleđivanje poruke';
$strForwardAlreadyDone = 'Poruka je već uspešno prosleđena na tu email adresu';
$strForwardCountReached = 'Dostignut je maksimalan broj prosleđivanja';
$strForwardNoteLimitReached = 'Dostignuta je maksimalna dužina lične napomene';
$strForwardFooter = 'Ova poruka Vam je prosleđena od strane [FORWARDEDBY].
  Niste automatski pretplaćeni na ovaj bilten.
  Da se pretplatite na ovaj bilten idite na';
$strForward = 'Prosledi';
$strFwd = 'Fwd'; # short version of forward for email subject


?>
