<?php

# language dependent text used in the interface for users (not admin)
# translation by Björn Pålsson <bjorn@pm-net.se>
# translated for version 2.10.4

$strCharSet             = 'UTF-8';
$strName                = 'Namn';
$strAddress             = 'Adress';
$strEmail               = 'E-postadress';
$strEmailrep		   = 'Repetera adress'; 
$strTown                = 'Ort';
$strPostcode            = 'Postnummer';
$strSubscribeInfo       = 'Anmäl dig till en eller flera av våra listor genom att fylla i formuläret nedan.';
$strRequired            = 'Oligatoriskt fält';
$strSubscribeTitle      = 'Anmäl dig till en av våra listor';
$strPleaseSelect        = 'Välj de listor du önskar att anmäla dig till';
$strSubmit              = 'Anmäl till de valda listorna';
$strNotAvailable        = 'Beklagar, det finns inga listor tillgängliga';
$strEnterName           = 'Skriv in ditt namn';
$strEnterEmail          = 'Skriv in din E-post adress';
$strInvalidHostInEmail  = 'Sorry, email to that domain is undeliverable, please check that you typed the correct email address';
$strEnterList           = 'Välj en lista du önskar att anmäla dig till';
$strThanks              = 'Tack för att du har anmält dig till en av våra listor.';
$strEmailConfirmation   = 'Du kommer snart att få ett E-brev med en bekräftelse på de listor du anmält dig till';
$strEnterList           = 'Please select a newsletter to subscribe to';
$strPleaseEnter         = 'Vänligen skriv in din';
# the thanks message can contain placeholders
#$strThanks              = 'Dear [FIRST NAME], <br/>Thank you for subscribing to our lists.';
$strThanks              = 'Tack för ditt intresse för våra nyhetsbrev.';
# the EmailConfirmation message can contain placeholders
$strEmailConfirmation   = 'Your email [email] has been added to our system. You will be e-mailed shortly with confirmation of the lists you have subscribed to.';
#$strEmailConfirmation   = 'Your email has been added to our system. You will be e-mailed shortly with a request to confirm your membership. Please make sure to click the link in that message to confirm your subscription.';
$strEmailFailed          = 'Sorry, sending the email to request your confirmation failed, please click "Reload" to try again. If it still does not work, it may be because you are listed on our "Black List", which means that you cannot receive emails from our newsletter system. In that case, please contact the administrator.';
$strUnsubscribeTitle    = 'Avanmäl dig från en av våra listor';
$strUnsubscribeDone     = 'Du är avanmäld från de valda listorna. Du kommer att få en bekräftelse inom kort.';
$strBack                = 'Tillbaka';
$strUnsubscribeInfo     = 'Avanmäl dig från en eller flera av våra listor';
$strContinue            = 'Fortsätt';
$strUnsubscribeSelect   = 'Välj de listor du önskar att avanmäla dig från';
$strAllLists            = 'Alla listor';
$strNoLists             = 'Ingen av dem';
$strNoListsFound        = 'Beklagar, du är inte anmäld till några av våra listor med den E-postadressen';
$strUnsubscribeRequestForReason = 'We are sorry to find you are not any longer interested in our newsletter. To help us improve our services, we would be grateful if you could tell us why:';
$strUnsubscribeFinalInfo = '<br/><b>Please note</b>: this page is to stop receiving emails from our newsletter system <b>forever</b>. If you want to change your email, or if you want to change which newsletters you receive, please <a href="[PREFERENCESURL]">update your preferences</a> instead';
$strResubmit            = 'Skicka E-brev igen';
$strUnsubscribeSubmit   = 'Avanmäl de valda listorna';
$strValuesMissing       = 'De följande obligatoriska fälten saknas';
$strConfirmInfo                 = 'Tack för bekräftelsen på anmälan till våra listor.<br />De listor du har anmält dig till visas nedan:';
$strConfirmTitle                = 'Bekräftelse på anmälan till nyhetsbrev';
$strUserNotFound        = 'Användare finns inte';
$strUserAlreadyInitialised = 'Beklagar, ditt lösenord är redan satt';
$strConfirmFailInfo     = 'Sorry, your request for confirmation was not recognised. Please make sure to use the full web address as mentioned in the email that you received. Sometimes this web address wraps onto multiple lines.';
$strPreferHTMLEmail     = 'Jag föredrar att få mina E-brev i HTML-format';
$strPreferTextEmail     = 'Jag föredrar att få mina E-brev i Textformat';
$strPreferredFormat      = 'Jag vill ha mina E-brev i:';
$strText                 = 'Text';
$strHTML                = 'HTML';
$strPreferencesTitle    = 'Uppdatera dina inställningar';
$strPreferencesInfo     = 'Vänligen bekräfta att uppgifterna nedan är korrekta och klicka på "Spara".';
$strUpdatePreferences   = 'Spara';
$strPreferencesEmailChanged = 'Your email has changed. Please visit the link in the email you will receive to confirm your new email address';
$strYouAreBlacklisted = 'Your email is listed in our "Black List", which means that you have requested us never to send you any more newsletters. <br/>
In order to receive emails again, manual intervention is required by our administrator. Please contact us stating explicitly that you want to receive newsletters again, and we will
take you off our black list. ';
$strPreferencesNotificationSent = 'Du kommer att få en bekräftelse på ändringarna';
$strPreferencesUpdated = 'Tack för att du håller dina uppgifter uppdaterarde.';
$strClickHere          = 'Klicka här';
$strThisLink           = 'denna länken';
$strToUnsubscribe      = 'Om du inte vill få fler nyhetsbrev skall du ';
$strToUpdate           = 'För att uppdatera dina uppgifter går du till ';
$strSendHTML           = 'Skicka HTML';
$strYes                = 'Ja';
$strNo                 = 'Nej';
$strUnsubscribe        = 'Avsluta';
$strAllMailinglists    = 'Alla nyhetsbrev';
$strAttachmentIntro     = 'Detta meddelande innehåller bilagor som kan visas i en webbläsare:';
$strLocation           = 'Plats';
$strFrequency           = 'Hur ofta skickar du meddelande';
$strHourly             = 'Varje timma';
$strDaily               = 'Dagligen';
$strWeekly             = 'Veckovis';
$strMonthly             = 'Månadsvis';
$strChoosePassword      = 'Välj ett lösenord';
$strConfirmPassword    = 'Bekräfta lösenordet';
$strEnterPassword       = 'Skriv in önskat lösenord';
$strForgotPassword     = 'Glömt lösenord';
$strPassword           = 'Lösenord';
$strPassword2           = 'Bekräfta lösenord';
$strPasswordsNoMatch    = 'Lösenorden är inte lika';
$strEmailsNoMatch     = 'E-postadresserna är inte lika';
$strInvalidPassword     = 'Fel: ogiltig E-postadress eller lösenord';
$strPasswordSent        = 'Ditt lösenord skickas till dig i ett e-brev. Du kommer att få det inom några minuter.';
$strPasswordRemindSubject = 'Ditt lösenord för vårt system';
$strPasswordRemindMessage = 'Ditt lösenord är ';
$strPasswordRemindInfo = 'Skriv in din E-postadress och tryck "'.$strForgotPassword.'" för att får lösenordet skickat till dig.';
$strLogin               = 'Login';
$strLoginTitle          = 'Skriv in E-postadress och lösenord';
$strLoginInfo           = 'Denna sidan kräver ett lösenord. '.$strLoginTitle;
$strPersonalLocationInfo = '<p>Denna sida kräver en personlig identifikationssträng som man hittar i varje meddelande vi skickar.<br/>
  Om du klickar på den länken och du trots det får detta meddelande skall du säkerställa att hela länken
  följer med till adressfältet i din webbläsare. Ibland kan adressen brytas upp på flera rader.</p>
  <p>Om du inte har denna adress kan du få ett meddelande tillsänt dig med länken.
  Skriv in din E-postadress och tryck "Continue".';
$strPersonalLocationSent = '<h1>Operationen lyckades! Du kommer att få ett meddelande med din personliga länk inom kort.</h1>';
$strUserExists   = '<br/>En användare med den E-postadressen finns redan och inte med detta lösenordet';
$strUserExistsExplanationStart = '<br/>För att få tillgång till ditt lösenord klickar du ';
$strUserExistsExplanationLink = 'här';
$strUserExistsExplanationEnd = ' för att gå till sidan där du kan efterfråga din personliga länk';
$strForwardTitle = 'Vidarebefordra ett meddelande till någon';
$strForwardSubtitle = 'Vidarebefordrar meddelandet med ämnet ';
$strForwardEnterEmail = 'Ange en giltig E-postadress att vidarebefordra till';
$strForwardSuccessInfo ='Detta meddelande är vidarebefordrat';
$strForwardFailInfo = 'Vidarebefordran fungerade inte';
$strForwardAlreadyDone = 'Detta meddelande är redan vidarebefordrat till den E-postadressen';
$strForwardFooter = 'Detta meddelande är vidarebefordrat till dig av [FORWARDEDBY].
  Du är inte automatiskt anmäld till nyhetsbrevet.
  För att anmäla dig kan du gå till';
$strForward = 'Vidarebefordra';
$strFwd = 'Fwd'; # short version of forward for email subject
?>
